[package]
name = "conduit-todo-face"
version = "0.1.0"
edition = "2021"

[dependencies]
conduit-todo-plot = { path = "../model" }
conduit-presentation = { path = "../../../semantics/presentation", default-features = false }

[dev-dependencies]
conduit-body = { path = "../../../architecture/body" }
conduit-core = { path = "../../../architecture/core" }
conduit-planner = { path = "../../../architecture/planner" }
conduit-plot = { path = "../../../architecture/plot" }
conduit-presentation = { path = "../../../semantics/presentation", features = ["plot-catalog"] }
