use std::fmt::Write;

use conduit_core::{CancellationPolicy, TerminalPolicy};
use conduit_runtime::lowering::MAXIMUM_KERNEL_PORTS_PER_NODE;

use crate::model::{
    GeneratedClueTarget, GeneratedConfigurationEntry, GeneratedConfigurationValue,
    GeneratedCordEndpoint, GeneratedEmbeddedPlan, GeneratedPort, GeneratedStaticNode,
};

impl GeneratedEmbeddedPlan {
    /// Render deterministic, allocator-free table declarations for inclusion
    /// from a firmware build script's `OUT_DIR`.
    #[must_use]
    pub fn render_rust_module(&self) -> String {
        let mut output = String::new();
        output.push_str("// Generated by conduit-embedded-build. Do not edit.\n");
        writeln!(
            output,
            "pub const GENERATED_EMBEDDED_PLAN_SCHEMA_VERSION: u32 = {};",
            self.schema_version
        )
        .expect("String writes cannot fail");
        render_string_constant(&mut output, "PLAN_ID", &self.plan_id);
        render_string_constant(&mut output, "FRAGMENT_ID", &self.fragment_id);
        render_string_constant(&mut output, "HOST_ID", &self.host_id);
        render_string_constant(&mut output, "BOOT_ID", &self.boot_id);
        writeln!(
            output,
            "pub const GENERATED_PORTS_PER_NODE: usize = {};",
            MAXIMUM_KERNEL_PORTS_PER_NODE
        )
        .expect("String writes cannot fail");
        writeln!(
            output,
            "pub const OFFER_GENERATION: u64 = {};",
            self.offer_generation
        )
        .expect("String writes cannot fail");
        render_policies(&mut output, self.cancellation_policy, self.terminal_policy);
        render_budgets(&mut output, self);
        render_nodes(&mut output, self);
        render_node_strings(
            &mut output,
            "GENERATED_PLACEMENT_IDS",
            &self.nodes,
            |node| &node.placement_id,
        );
        render_node_strings(&mut output, "GENERATED_KIND_IDS", &self.nodes, |node| {
            &node.kind_id
        });
        render_node_strings(
            &mut output,
            "GENERATED_IMPLEMENTATION_IDS",
            &self.nodes,
            |node| &node.implementation_id,
        );
        render_node_strings(&mut output, "GENERATED_ARTIFACT_IDS", &self.nodes, |node| {
            &node.artifact_id
        });
        render_ports(&mut output, "GENERATED_INPUT_PORTS", &self.input_ports);
        render_ports(&mut output, "GENERATED_OUTPUT_PORTS", &self.output_ports);
        render_configuration(&mut output, &self.configuration);
        render_cords(&mut output, self);
        render_remote_endpoints(&mut output, self);
        render_routes(&mut output, self);
        render_host_operations(&mut output, self);
        render_resources(&mut output, self);
        render_clue(&mut output, self);
        render_startup(&mut output, self);
        render_expected_terminals(&mut output, self);
        output
    }

    /// Render deterministic fixed tables without references to `conduit_core`.
    ///
    /// This variant is intended for allocator-free firmware images. The host
    /// generator has already validated and copied current plan facts; firmware
    /// consumes only primitive identity/configuration projections and kernel
    /// tables.
    #[must_use]
    pub fn render_no_alloc_firmware_module(&self) -> String {
        let mut output = String::new();
        output.push_str("// Generated by conduit-embedded-build. Do not edit.\n");
        output.push_str("#[derive(Clone, Copy, Debug, Eq, PartialEq)]\n");
        output.push_str("pub enum GeneratedConfigurationValue { Bool(bool), U64(u64) }\n");
        writeln!(
            output,
            "pub const GENERATED_EMBEDDED_PLAN_SCHEMA_VERSION: u32 = {};",
            self.schema_version
        )
        .expect("String writes cannot fail");
        render_string_constant(&mut output, "PLAN_ID", &self.plan_id);
        render_string_constant(&mut output, "FRAGMENT_ID", &self.fragment_id);
        render_string_constant(&mut output, "HOST_ID", &self.host_id);
        render_string_constant(&mut output, "BOOT_ID", &self.boot_id);
        writeln!(
            output,
            "pub const GENERATED_PORTS_PER_NODE: usize = {};",
            MAXIMUM_KERNEL_PORTS_PER_NODE
        )
        .expect("String writes cannot fail");
        writeln!(
            output,
            "pub const OFFER_GENERATION: u64 = {};",
            self.offer_generation
        )
        .expect("String writes cannot fail");
        render_policy_strings(&mut output, self.cancellation_policy, self.terminal_policy);
        render_budgets(&mut output, self);
        render_nodes(&mut output, self);
        render_node_strings(
            &mut output,
            "GENERATED_PLACEMENT_IDS",
            &self.nodes,
            |node| &node.placement_id,
        );
        render_node_strings(&mut output, "GENERATED_KIND_IDS", &self.nodes, |node| {
            &node.kind_id
        });
        render_node_strings(
            &mut output,
            "GENERATED_IMPLEMENTATION_IDS",
            &self.nodes,
            |node| &node.implementation_id,
        );
        render_node_strings(&mut output, "GENERATED_ARTIFACT_IDS", &self.nodes, |node| {
            &node.artifact_id
        });
        render_ports(&mut output, "GENERATED_INPUT_PORTS", &self.input_ports);
        render_ports(&mut output, "GENERATED_OUTPUT_PORTS", &self.output_ports);
        render_no_alloc_configuration(&mut output, &self.configuration);
        render_cords(&mut output, self);
        render_remote_endpoints(&mut output, self);
        render_routes(&mut output, self);
        render_host_operations(&mut output, self);
        render_resources(&mut output, self);
        render_clue(&mut output, self);
        render_startup(&mut output, self);
        render_expected_terminals(&mut output, self);
        output
    }
}

fn render_policies(
    output: &mut String,
    cancellation: CancellationPolicy,
    terminal: TerminalPolicy,
) {
    let cancellation = match cancellation {
        CancellationPolicy::CancelAllAndRejectLateCompletion => {
            "conduit_core::CancellationPolicy::CancelAllAndRejectLateCompletion"
        }
        CancellationPolicy::DrainBeforeCancel => {
            "conduit_core::CancellationPolicy::DrainBeforeCancel"
        }
    };
    let terminal = match terminal {
        TerminalPolicy::RequireAllPlacementsAndConnections => {
            "conduit_core::TerminalPolicy::RequireAllPlacementsAndConnections"
        }
        TerminalPolicy::RequirePlacementsOnly => {
            "conduit_core::TerminalPolicy::RequirePlacementsOnly"
        }
    };
    writeln!(
        output,
        "pub const CANCELLATION_POLICY: conduit_core::CancellationPolicy = {cancellation};"
    )
    .expect("String writes cannot fail");
    writeln!(
        output,
        "pub const TERMINAL_POLICY: conduit_core::TerminalPolicy = {terminal};"
    )
    .expect("String writes cannot fail");
}

fn render_policy_strings(
    output: &mut String,
    cancellation: CancellationPolicy,
    terminal: TerminalPolicy,
) {
    let cancellation = match cancellation {
        CancellationPolicy::CancelAllAndRejectLateCompletion => "CancelAllAndRejectLateCompletion",
        CancellationPolicy::DrainBeforeCancel => "DrainBeforeCancel",
    };
    let terminal = match terminal {
        TerminalPolicy::RequireAllPlacementsAndConnections => "RequireAllPlacementsAndConnections",
        TerminalPolicy::RequirePlacementsOnly => "RequirePlacementsOnly",
    };
    render_string_constant(output, "CANCELLATION_POLICY", cancellation);
    render_string_constant(output, "TERMINAL_POLICY", terminal);
}

fn render_budgets(output: &mut String, plan: &GeneratedEmbeddedPlan) {
    for (name, kind, value) in [
        ("CORD_VALUE_SLOTS", "u16", u64::from(plan.cord_value_slots)),
        ("CORD_VALUE_BYTES", "u32", u64::from(plan.cord_value_bytes)),
        ("CLUE_ITEMS", "u16", u64::from(plan.clue_items)),
        ("CLUE_BYTES", "u32", u64::from(plan.clue_bytes)),
    ] {
        writeln!(output, "pub const {name}: {kind} = {value};").expect("String writes cannot fail");
    }
}

fn render_nodes(output: &mut String, plan: &GeneratedEmbeddedPlan) {
    writeln!(
        output,
        "pub const GENERATED_NODES: [conduit_kernel::scheduler::NodeSpec<{}>; {}] = [",
        MAXIMUM_KERNEL_PORTS_PER_NODE,
        plan.nodes.len()
    )
    .expect("String writes cannot fail");
    for node in &plan.nodes {
        output.push_str("    conduit_kernel::scheduler::NodeSpec { input_cords: [");
        for cord in node.input_cords {
            match cord {
                Some(cord) => write!(output, "Some(conduit_kernel::CordId({cord})),")
                    .expect("String writes cannot fail"),
                None => output.push_str("None,"),
            }
        }
        writeln!(
            output,
            "], maximum_step_work: {} }},",
            node.maximum_step_work
        )
        .expect("String writes cannot fail");
    }
    output.push_str("];\n");
}

fn render_cords(output: &mut String, plan: &GeneratedEmbeddedPlan) {
    writeln!(
        output,
        "pub const GENERATED_CORDS: [conduit_kernel::scheduler::CordSpec; {}] = [",
        plan.cords.len()
    )
    .expect("String writes cannot fail");
    for cord in &plan.cords {
        let source = match cord.source {
            GeneratedCordEndpoint::Local { node, port } => format!(
                "conduit_kernel::CordEndpoint::local(conduit_kernel::NodeId({node}), conduit_kernel::PortId({port}))"
            ),
            GeneratedCordEndpoint::Remote { endpoint } => format!(
                "conduit_kernel::CordEndpoint::Remote(conduit_kernel::RemoteEndpointId({endpoint}))"
            ),
        };
        let sink = match cord.sink {
            GeneratedCordEndpoint::Local { node, port } => format!(
                "conduit_kernel::CordEndpoint::local(conduit_kernel::NodeId({node}), conduit_kernel::PortId({port}))"
            ),
            GeneratedCordEndpoint::Remote { endpoint } => format!(
                "conduit_kernel::CordEndpoint::Remote(conduit_kernel::RemoteEndpointId({endpoint}))"
            ),
        };
        writeln!(
            output,
            "    conduit_kernel::scheduler::CordSpec {{ cord: conduit_kernel::CordId({}), source: {}, sink: {}, slot_start: {}, item_capacity: {}, byte_capacity: {} }},",
            cord.cord,
            source,
            sink,
            cord.slot_start,
            cord.item_capacity,
            cord.byte_capacity
        )
        .expect("String writes cannot fail");
    }
    output.push_str("];\n");
    render_string_slice(
        output,
        "GENERATED_CONNECTION_IDS",
        plan.cords.iter().map(|cord| cord.connection_id.as_str()),
    );
}

fn render_routes(output: &mut String, plan: &GeneratedEmbeddedPlan) {
    writeln!(
        output,
        "pub const GENERATED_ROUTES: [(conduit_kernel::NodeId, conduit_kernel::PortId, conduit_kernel::RouteRange); {}] = [",
        plan.routes.len()
    )
    .expect("String writes cannot fail");
    for route in &plan.routes {
        writeln!(
            output,
            "    (conduit_kernel::NodeId({}), conduit_kernel::PortId({}), conduit_kernel::RouteRange {{ start: {}, len: {} }}),",
            route.source_node, route.source_port, route.target_start, route.target_len
        )
        .expect("String writes cannot fail");
    }
    output.push_str("];\n");

    writeln!(
        output,
        "pub const GENERATED_ROUTE_TARGETS: [conduit_kernel::RouteTarget; {}] = [",
        plan.route_targets.len()
    )
    .expect("String writes cannot fail");
    for target in &plan.route_targets {
        writeln!(
            output,
            "    conduit_kernel::RouteTarget {{ cord: conduit_kernel::CordId({}), sink: conduit_kernel::CordEndpoint::local(conduit_kernel::NodeId({}), conduit_kernel::PortId({})) }},",
            target.cord, target.sink_node, target.sink_port
        )
        .expect("String writes cannot fail");
    }
    output.push_str("];\n");
}

fn render_host_operations(output: &mut String, plan: &GeneratedEmbeddedPlan) {
    writeln!(
        output,
        "pub const GENERATED_HOST_OPERATIONS: [(conduit_kernel::NodeId, conduit_kernel::HostOperationBinding); {}] = [",
        plan.host_operations.len()
    )
    .expect("String writes cannot fail");
    for operation in &plan.host_operations {
        writeln!(
            output,
            "    (conduit_kernel::NodeId({}), conduit_kernel::HostOperationBinding {{ operation: conduit_kernel::HostOperationId({}), maximum_input_bytes: {}, maximum_output_bytes: {} }}),",
            operation.node,
            operation.operation,
            operation.maximum_input_bytes,
            operation.maximum_output_bytes
        )
        .expect("String writes cannot fail");
    }
    output.push_str("];\n");

    writeln!(
        output,
        "pub const GENERATED_HOST_OPERATION_IDENTITIES: [(&str, Option<&str>, u16); {}] = [",
        plan.host_operations.len()
    )
    .expect("String writes cannot fail");
    for operation in &plan.host_operations {
        let target = operation
            .target_kind
            .as_deref()
            .map_or_else(|| "None".to_owned(), |value| format!("Some({value:?})"));
        writeln!(
            output,
            "    ({:?}, {}, {}),",
            operation.contract_id, target, operation.maximum_in_flight
        )
        .expect("String writes cannot fail");
    }
    output.push_str("];\n");
}

fn render_resources(output: &mut String, plan: &GeneratedEmbeddedPlan) {
    writeln!(
        output,
        "pub const GENERATED_RESOURCES: [(conduit_kernel::NodeId, conduit_kernel::ResourceBinding); {}] = [",
        plan.resources.len()
    )
    .expect("String writes cannot fail");
    for resource in &plan.resources {
        writeln!(
            output,
            "    (conduit_kernel::NodeId({}), conduit_kernel::ResourceBinding {{ resource: conduit_kernel::ResourceId({}), units: {} }}),",
            resource.node, resource.resource, resource.units
        )
        .expect("String writes cannot fail");
    }
    output.push_str("];\n");
}

fn render_clue(output: &mut String, plan: &GeneratedEmbeddedPlan) {
    writeln!(
        output,
        "pub const GENERATED_CLUE_TARGETS: [(conduit_kernel::ClueExpectationId, conduit_kernel::ClueExpectationTarget); {}] = [",
        plan.clues.len()
    )
    .expect("String writes cannot fail");
    for clue in &plan.clues {
        let target = match clue.target {
            GeneratedClueTarget::Fragment => {
                "conduit_kernel::ClueExpectationTarget::Fragment".to_owned()
            }
            GeneratedClueTarget::Node(node) => format!(
                "conduit_kernel::ClueExpectationTarget::Node(conduit_kernel::NodeId({node}))"
            ),
            GeneratedClueTarget::Cord(cord) => format!(
                "conduit_kernel::ClueExpectationTarget::Cord(conduit_kernel::CordId({cord}))"
            ),
        };
        writeln!(
            output,
            "    (conduit_kernel::ClueExpectationId({}), {}),",
            clue.expectation, target
        )
        .expect("String writes cannot fail");
    }
    output.push_str("];\n");

    writeln!(
        output,
        "pub const GENERATED_CLUE_IDENTITIES: [(&str, Option<&str>); {}] = [",
        plan.clues.len()
    )
    .expect("String writes cannot fail");
    for clue in &plan.clues {
        render_kind_subject(output, clue.kind, clue.subject.as_deref());
    }
    output.push_str("];\n");
}

fn render_startup(output: &mut String, plan: &GeneratedEmbeddedPlan) {
    writeln!(
        output,
        "pub const GENERATED_STARTUP_DEPENDENCIES: [(conduit_kernel::NodeId, conduit_kernel::NodeId); {}] = [",
        plan.startup_dependencies.len()
    )
    .expect("String writes cannot fail");
    for dependency in &plan.startup_dependencies {
        writeln!(
            output,
            "    (conduit_kernel::NodeId({}), conduit_kernel::NodeId({})),",
            dependency.prerequisite_node, dependency.dependent_node
        )
        .expect("String writes cannot fail");
    }
    output.push_str("];\n");

    write!(
        output,
        "pub const GENERATED_STARTUP_ORDER: [conduit_kernel::NodeId; {}] = [",
        plan.startup_order.len()
    )
    .expect("String writes cannot fail");
    for node in &plan.startup_order {
        write!(output, "conduit_kernel::NodeId({node}),").expect("String writes cannot fail");
    }
    output.push_str("];\n");
}

fn render_expected_terminals(output: &mut String, plan: &GeneratedEmbeddedPlan) {
    writeln!(
        output,
        "pub const GENERATED_EXPECTED_TERMINALS: [(&str, Option<&str>); {}] = [",
        plan.expected_terminals.len()
    )
    .expect("String writes cannot fail");
    for terminal in &plan.expected_terminals {
        render_kind_subject(output, terminal.kind, terminal.subject.as_deref());
    }
    output.push_str("];\n");
}

fn render_string_constant(output: &mut String, name: &str, value: &str) {
    writeln!(output, "pub const {name}: &str = {value:?};").expect("String writes cannot fail");
}

fn render_node_strings(
    output: &mut String,
    name: &str,
    nodes: &[GeneratedStaticNode],
    select: impl Fn(&GeneratedStaticNode) -> &str,
) {
    render_string_slice(output, name, nodes.iter().map(select));
}

fn render_string_slice<'a>(
    output: &mut String,
    name: &str,
    values: impl IntoIterator<Item = &'a str>,
) {
    let values = values.into_iter().collect::<Vec<_>>();
    writeln!(output, "pub const {name}: [&str; {}] = [", values.len())
        .expect("String writes cannot fail");
    for value in values {
        writeln!(output, "    {value:?},").expect("String writes cannot fail");
    }
    output.push_str("];\n");
}

fn render_ports(output: &mut String, name: &str, ports: &[GeneratedPort]) {
    writeln!(
        output,
        "pub const {name}: [(conduit_kernel::NodeId, conduit_kernel::PortId, &str, &str); {}] = [",
        ports.len()
    )
    .expect("String writes cannot fail");
    for port in ports {
        writeln!(
            output,
            "    (conduit_kernel::NodeId({}), conduit_kernel::PortId({}), {:?}, {:?}),",
            port.node, port.port, port.port_id, port.value_kind
        )
        .expect("String writes cannot fail");
    }
    output.push_str("];\n");
}

fn render_configuration(output: &mut String, configuration: &[GeneratedConfigurationEntry]) {
    writeln!(
        output,
        "pub const GENERATED_CONFIGURATION: [(conduit_kernel::NodeId, &str, conduit_core::ConfigurationValue); {}] = [",
        configuration.len()
    )
    .expect("String writes cannot fail");
    for entry in configuration {
        let value = match entry.value {
            GeneratedConfigurationValue::Bool(value) => {
                format!("conduit_core::ConfigurationValue::Bool({value})")
            }
            GeneratedConfigurationValue::U64(value) => {
                format!("conduit_core::ConfigurationValue::U64({value})")
            }
        };
        writeln!(
            output,
            "    (conduit_kernel::NodeId({}), {:?}, {}),",
            entry.node, entry.key, value
        )
        .expect("String writes cannot fail");
    }
    output.push_str("];\n");
}

fn render_no_alloc_configuration(
    output: &mut String,
    configuration: &[GeneratedConfigurationEntry],
) {
    writeln!(
        output,
        "pub const GENERATED_CONFIGURATION: [(conduit_kernel::NodeId, &str, GeneratedConfigurationValue); {}] = [",
        configuration.len()
    )
    .expect("String writes cannot fail");
    for entry in configuration {
        let value = match entry.value {
            GeneratedConfigurationValue::Bool(value) => {
                format!("GeneratedConfigurationValue::Bool({value})")
            }
            GeneratedConfigurationValue::U64(value) => {
                format!("GeneratedConfigurationValue::U64({value})")
            }
        };
        writeln!(
            output,
            "    (conduit_kernel::NodeId({}), {:?}, {}),",
            entry.node, entry.key, value
        )
        .expect("String writes cannot fail");
    }
    output.push_str("];\n");
}

fn render_kind_subject(output: &mut String, kind: &str, subject: Option<&str>) {
    let subject = subject.map_or_else(|| "None".to_owned(), |value| format!("Some({value:?})"));
    writeln!(output, "    ({kind:?}, {subject}),").expect("String writes cannot fail");
}

fn render_remote_endpoints(output: &mut String, plan: &GeneratedEmbeddedPlan) {
    writeln!(
        output,
        "pub const GENERATED_REMOTE_ENDPOINT_COUNT: usize = {};",
        plan.remote_endpoints.len()
    )
    .expect("String writes cannot fail");

    render_string_slice(
        output,
        "GENERATED_REMOTE_ENDPOINT_CONNECTION_IDS",
        plan.remote_endpoints
            .iter()
            .map(|re| re.connection_id.as_str()),
    );
    render_u16_slice(
        output,
        "GENERATED_REMOTE_ENDPOINT_IDS",
        plan.remote_endpoints.iter().map(|re| re.endpoint),
    );
    render_u16_slice(
        output,
        "GENERATED_REMOTE_ENDPOINT_CORDS",
        plan.remote_endpoints.iter().map(|re| re.cord),
    );
    render_string_slice(
        output,
        "GENERATED_REMOTE_ENDPOINT_SOURCE_FRAGMENT_IDS",
        plan.remote_endpoints
            .iter()
            .map(|re| re.source_fragment_id.as_str()),
    );
    render_string_slice(
        output,
        "GENERATED_REMOTE_ENDPOINT_LOCAL_HOSTS",
        plan.remote_endpoints
            .iter()
            .map(|re| re.local_host.as_str()),
    );
    render_string_slice(
        output,
        "GENERATED_REMOTE_ENDPOINT_LOCAL_BOOTS",
        plan.remote_endpoints
            .iter()
            .map(|re| re.local_boot.as_str()),
    );
    render_string_slice(
        output,
        "GENERATED_REMOTE_ENDPOINT_LOCAL_ENDPOINTS",
        plan.remote_endpoints
            .iter()
            .map(|re| re.local_endpoint.as_str()),
    );
    render_string_slice(
        output,
        "GENERATED_REMOTE_ENDPOINT_PEER_HOSTS",
        plan.remote_endpoints.iter().map(|re| re.peer_host.as_str()),
    );
    render_string_slice(
        output,
        "GENERATED_REMOTE_ENDPOINT_PEER_BOOTS",
        plan.remote_endpoints.iter().map(|re| re.peer_boot.as_str()),
    );
    render_string_slice(
        output,
        "GENERATED_REMOTE_ENDPOINT_PEER_ENDPOINTS",
        plan.remote_endpoints
            .iter()
            .map(|re| re.peer_endpoint.as_str()),
    );
    render_string_slice(
        output,
        "GENERATED_REMOTE_ENDPOINT_SINK_FRAGMENT_IDS",
        plan.remote_endpoints
            .iter()
            .map(|re| re.sink_fragment_id.as_str()),
    );
    render_u8_slice(
        output,
        "GENERATED_REMOTE_ENDPOINT_BASE_CODES",
        plan.remote_endpoints
            .iter()
            .map(|re| re.base.canonical_code()),
    );
    render_string_slice(
        output,
        "GENERATED_REMOTE_ENDPOINT_LINK_BINDING_IDS",
        plan.remote_endpoints
            .iter()
            .map(|re| re.link_binding_id.as_str()),
    );
    render_string_slice(
        output,
        "GENERATED_REMOTE_ENDPOINT_BASE_INSTANCE_IDS",
        plan.remote_endpoints
            .iter()
            .map(|re| re.base_instance_id.as_str()),
    );
    render_string_slice(
        output,
        "GENERATED_REMOTE_ENDPOINT_VALUE_KINDS",
        plan.remote_endpoints
            .iter()
            .map(|re| re.value_kind.as_str()),
    );
    render_u16_slice(
        output,
        "GENERATED_REMOTE_ENDPOINT_MAXIMUM_IN_FLIGHT_ITEMS",
        plan.remote_endpoints
            .iter()
            .map(|re| re.maximum_in_flight_items),
    );
    render_u32_slice(
        output,
        "GENERATED_REMOTE_ENDPOINT_MAXIMUM_PAYLOAD_BYTES",
        plan.remote_endpoints
            .iter()
            .map(|re| re.maximum_payload_bytes),
    );
    render_u32_slice(
        output,
        "GENERATED_REMOTE_ENDPOINT_MAXIMUM_BUFFERED_BYTES",
        plan.remote_endpoints
            .iter()
            .map(|re| re.maximum_buffered_bytes),
    );
    render_u32_slice(
        output,
        "GENERATED_REMOTE_ENDPOINT_MAXIMUM_FRAME_BYTES",
        plan.remote_endpoints
            .iter()
            .map(|re| re.maximum_frame_bytes),
    );
}

fn render_u8_slice(output: &mut String, name: &str, values: impl Iterator<Item = u8>) {
    let values = values.collect::<Vec<_>>();
    writeln!(
        output,
        "pub const {name}: [u8; {}] = {:?};",
        values.len(),
        values
    )
    .expect("String writes cannot fail");
}

fn render_u16_slice(output: &mut String, name: &str, values: impl Iterator<Item = u16>) {
    let values = values.collect::<Vec<_>>();
    writeln!(
        output,
        "pub const {name}: [u16; {}] = {:?};",
        values.len(),
        values
    )
    .expect("String writes cannot fail");
}

fn render_u32_slice(output: &mut String, name: &str, values: impl Iterator<Item = u32>) {
    let values = values.collect::<Vec<_>>();
    writeln!(
        output,
        "pub const {name}: [u32; {}] = {:?};",
        values.len(),
        values
    )
    .expect("String writes cannot fail");
}
