[package]
name = "patchbay-native"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
conduit-core = { path = "../../crates/conduit-core" }
conduit-observatory = { path = "../../crates/conduit-observatory" }
conduit-presentation = { path = "../../crates/conduit-presentation" }
conduit-std-catalog = { path = "../../crates/conduit-std-catalog", features = ["form-catalog"] }
conduit-std-host = { path = "../std" }
embedded-graphics = "=0.8.1"
patchbay-model = { path = "../patchbay-model" }
serde_json = "1"
softbuffer = { version = "0.4", default-features = false, features = ["wayland", "wayland-dlopen"] }
winit = { version = "0.30", default-features = false, features = ["rwh_06", "wayland", "wayland-dlopen"] }
