/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const cancel_panel: (a: number, b: number) => [number, number];
export const explain_panel: (a: number, b: number) => [number, number];
export const panel_language_metadata: () => [number, number];
export const panel_source_metadata: (a: number, b: number) => [number, number];
export const parse_panel: (a: number, b: number) => [number, number];
export const patchbay_advance_exact_run: (a: number, b: number, c: bigint) => [number, number];
export const patchbay_apply_transaction: (a: number, b: number, c: number, d: number) => [number, number];
export const patchbay_attach_exact_watch: (a: number, b: number, c: number, d: number) => [number, number];
export const patchbay_cancel_exact_run: (a: number, b: number, c: number, d: number) => [number, number];
export const patchbay_detach_exact_watch: (a: number, b: number, c: number, d: number) => [number, number];
export const patchbay_move_node: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number];
export const patchbay_notify_host_operation: (a: number, b: number, c: number, d: number) => [number, number];
export const patchbay_open_session: (a: number, b: number, c: number, d: number) => [number, number];
export const patchbay_pump_exact_run: (a: number, b: number, c: bigint) => [number, number];
export const patchbay_read_exact_evidence: (a: number, b: number, c: bigint, d: number) => [number, number];
export const patchbay_read_exact_watch: (a: number, b: number, c: number, d: number, e: bigint, f: number) => [number, number];
export const patchbay_replace_source: (a: number, b: number, c: number, d: number) => [number, number];
export const patchbay_session_view: (a: number, b: number) => [number, number];
export const patchbay_start_exact_run: (a: number, b: number) => [number, number];
export const run_panel: (a: number, b: number) => [number, number];
export const run_panel_compatibility_demo: (a: number, b: number) => [number, number];
export const run_panel_exact: (a: number, b: number, c: number, d: number) => [number, number];
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
