use serde::Serialize;

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub(super) enum ProofKind {
    Workspace,
    Browser,
    Machine,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub(super) enum Applicability {
    CandidateAndIntegration,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(super) enum Selection {
    CiController,
    SharedCompile,
    WorkspaceShard(&'static str),
    PagesProducts,
    PagesProductProof(&'static str),
    Esp32Required,
    Esp32Target(&'static str),
    ConduitosRequired,
    ConduitosX86(&'static str),
    ConduitosArchitecture(&'static str),
    ConduitosAarch64Product,
}

#[derive(Clone, Copy, Debug)]
pub(super) struct ProofSpec {
    pub(super) id: &'static str,
    pub(super) contract_version: u32,
    pub(super) kind: ProofKind,
    // Required source domains must exist in every candidate tree.
    pub(super) inputs: &'static [&'static str],
    // Exact Git selectors, including absent paths: moves/deletions change receipts.
    pub(super) implementation_inputs: &'static [&'static str],
    pub(super) consumed_artifacts: &'static [&'static str],
    pub(super) environment: &'static str,
    pub(super) applicability: Applicability,
    pub(super) selection: Selection,
    pub(super) command: &'static str,
}

macro_rules! conduitos_proof {
    ($id:literal, $selection:expr, $environment:literal, $command:literal) => {
        ProofSpec {
            id: $id,
            contract_version: 1,
            kind: ProofKind::Machine,
            inputs: &[
                "Cargo.toml",
                "Cargo.lock",
                "architecture",
                "semantics",
                "targets/conduitos",
            ],
            implementation_inputs: &[".github/workflows/check.yml"],
            consumed_artifacts: &[],
            environment: $environment,
            applicability: Applicability::CandidateAndIntegration,
            selection: $selection,
            command: $command,
        }
    };
}

// This first registry slice names broad, reviewable domains. Missing knowledge
// fails closed by selecting the broader domain; later slices can split a node
// without changing the proof-key or receipt contract.
pub(super) const PROOFS: &[ProofSpec] = &[
    ProofSpec {
        id: "ci.controller-contracts",
        contract_version: 1,
        kind: ProofKind::Workspace,
        inputs: &[
            ".github/workflows/check.yml",
            ".github/workflows/reconcile-candidate.yml",
            ".github/workflows/retire-merged-pr-branch.yml",
            ".github/workflows/retire-superseded-candidates.yml",
            "tools",
            "proof/ci",
        ],
        implementation_inputs: &["proof/ci", "tools/ci", "tools/xtask/src/commands/ci", "tools/xtask/tests/ci_workflow_contract.rs", "tools"],
        consumed_artifacts: &[],
        environment: "ubuntu-rust-1.98.1-node-v1",
        applicability: Applicability::CandidateAndIntegration,
        selection: Selection::CiController,
        command: "cargo test --locked --package conduit-xtask-dispatch && node --test proof/ci/check-result-gate.spec.mjs proof/ci/retire-superseded-candidates.spec.mjs proof/ci/reconcile-candidate-request.spec.mjs",
    },
    ProofSpec {
        id: "workspace.shared-compile",
        contract_version: 1,
        kind: ProofKind::Workspace,
        inputs: &[
            "Cargo.toml",
            "Cargo.lock",
            "architecture",
            "fabrication",
            "mechanisms",
            "products",
            "semantics",
            "targets",
        ],
        implementation_inputs: &[
            ".github/workflows",
            "tools/xtask/src/commands/ci/impact.rs",
            "tools",
        ],
        consumed_artifacts: &[],
        environment: "ubuntu-rust-1.98.1-shared-compile-v1",
        applicability: Applicability::CandidateAndIntegration,
        selection: Selection::SharedCompile,
        command: "cargo check --locked -p <each changed shared package>",
    },
    ProofSpec {
        id: "workspace.lint",
        contract_version: 1,
        kind: ProofKind::Workspace,
        inputs: &["Cargo.toml", "Cargo.lock", "architecture", "fabrication", "mechanisms", "products", "semantics", "targets", "tools"],
        implementation_inputs: &["tools/xtask", "tools", ".github/workflows/check.yml"],
        consumed_artifacts: &[],
        environment: "ubuntu-rust-1.98.1-clippy-rustfmt-v1",
        applicability: Applicability::CandidateAndIntegration,
        selection: Selection::WorkspaceShard("lint"),
        command: "cargo xtask check workspace-lint --locked",
    },
    ProofSpec {
        id: "workspace.foundation",
        contract_version: 1,
        kind: ProofKind::Workspace,
        inputs: &["Cargo.toml", "Cargo.lock", "architecture", "mechanisms", "semantics"],
        implementation_inputs: &["tools/xtask", "tools", ".github/workflows/check.yml"],
        consumed_artifacts: &[],
        environment: "ubuntu-rust-1.98.1-v1",
        applicability: Applicability::CandidateAndIntegration,
        selection: Selection::WorkspaceShard("test-foundation"),
        command: "cargo xtask check workspace-test-foundation --locked",
    },
    ProofSpec {
        id: "workspace.hosts",
        contract_version: 1,
        kind: ProofKind::Workspace,
        inputs: &["Cargo.toml", "Cargo.lock", "fabrication", "targets"],
        implementation_inputs: &["tools/xtask", "tools", ".github/workflows/check.yml"],
        consumed_artifacts: &[],
        environment: "ubuntu-rust-1.98.1-v1",
        applicability: Applicability::CandidateAndIntegration,
        selection: Selection::WorkspaceShard("test-hosts"),
        command: "cargo xtask check workspace-test-hosts --locked",
    },
    ProofSpec {
        id: "workspace.products",
        contract_version: 2,
        kind: ProofKind::Workspace,
        inputs: &[
            "Cargo.toml",
            "Cargo.lock",
            "architecture",
            "fabrication",
            "semantics",
            "products",
            "bodies",
            "targets/std",
        ],
        implementation_inputs: &[
            "tools/xtask/src/commands/check.rs",
            "tools",
            "tools/xtask/src/suites",
            ".github/workflows/check.yml",
        ],
        consumed_artifacts: &[],
        environment: "ubuntu-rust-1.98.1-v1",
        applicability: Applicability::CandidateAndIntegration,
        selection: Selection::WorkspaceShard("test-products"),
        command: "cargo xtask check workspace-test-products --locked",
    },
    ProofSpec {
        id: "workspace.portable",
        contract_version: 1,
        kind: ProofKind::Workspace,
        inputs: &["Cargo.toml", "Cargo.lock", "architecture", "mechanisms", "semantics", "targets/std"],
        implementation_inputs: &["tools/xtask", "tools", ".github/workflows/check.yml"],
        consumed_artifacts: &[],
        environment: "ubuntu-rust-1.98.1-wasm-thumbv6m-v1",
        applicability: Applicability::CandidateAndIntegration,
        selection: Selection::WorkspaceShard("portable"),
        command: "cargo xtask check workspace-portable --locked",
    },
    ProofSpec {
        id: "workspace.pico",
        contract_version: 1,
        kind: ProofKind::Workspace,
        inputs: &["Cargo.toml", "Cargo.lock", "architecture", "bodies", "semantics", "targets/rp2040"],
        implementation_inputs: &["tools/xtask", "tools", ".github/workflows/check.yml"],
        consumed_artifacts: &[],
        environment: "ubuntu-rust-1.98.1-thumbv6m-v1",
        applicability: Applicability::CandidateAndIntegration,
        selection: Selection::WorkspaceShard("pico"),
        command: "cargo xtask check workspace-pico --locked",
    },
    ProofSpec {
        id: "browser.tour",
        contract_version: 3,
        kind: ProofKind::Browser,
        inputs: &[
            "Cargo.toml",
            "Cargo.lock",
            "architecture/form",
            "architecture/kernel",
            "targets/browser",
            "products/patchbay/html",
            "products/tour",
            "products/creche",
            "site",
        ],
        // Fingerprint complete owning domains so a trusted controller can
        // validate a candidate that renames proof, staging, or workflow files.
        // Paths and bytes remain hashed; renames invalidate prior receipts.
        implementation_inputs: &["proof/browser", "proof/ci", "tools/ci", "tools", "proof/browser/package.json", "proof/browser/package-lock.json", "targets/browser/tools", "products/tour/tools", "products/creche/tools", "products/patchbay/tools", "site/tools", ".github/workflows"],
        consumed_artifacts: &[],
        environment: "playwright-chromium-1.62.0-noble-worker1-retry0",
        applicability: Applicability::CandidateAndIntegration,
        selection: Selection::PagesProducts,
        command: "node proof/browser/node_modules/@playwright/test/cli.js test --config proof/browser/playwright.config.mjs proof/browser/executable-tour.spec.mjs --project chromium --workers 1 --retries 0",
    },
    ProofSpec {
        id: "browser.patchbay-debugger",
        contract_version: 2,
        kind: ProofKind::Browser,
        inputs: &[
            "Cargo.toml",
            "Cargo.lock",
            "proof/browser",
            "architecture/kernel/src/debug_observation.rs",
            "architecture/kernel/src/debug_observation",
            "architecture/kernel/src/scheduler.rs",
            "architecture/kernel/src/scheduler/debug_control.rs",
            "architecture/kernel/tests/debug_observation.rs",
            "products/patchbay/html",
            "products/patchbay/model",
            "semantics/tongues",
        ],
        // Fingerprint complete owning domains so a trusted controller can
        // validate a candidate that renames proof, staging, or workflow files.
        // Paths and bytes remain hashed; renames invalidate prior receipts.
        implementation_inputs: &["proof/browser", "proof/ci", "tools/ci", "tools", "proof/browser/package.json", "proof/browser/package-lock.json", "targets/browser/tools", "products/tour/tools", "products/creche/tools", "products/patchbay/tools", "site/tools", ".github/workflows"],
        consumed_artifacts: &[],
        environment: "playwright-chromium-1.62.0-noble-worker1-retry0",
        applicability: Applicability::CandidateAndIntegration,
        selection: Selection::PagesProductProof("products.patchbay-debugger"),
        command: "cargo test --locked -p patchbay-model debugger_ && cargo test --locked -p conduit-kernel --test debug_observation && node proof/browser/node_modules/@playwright/test/cli.js test --config proof/browser/patchbay-debugger.config.mjs proof/browser/patchbay-debugger-watch.spec.mjs --project chromium --workers 1 --retries 0",
    },
    ProofSpec {
        id: "products.pages-carrier",
        contract_version: 3,
        kind: ProofKind::Browser,
        inputs: &[
            "Cargo.toml",
            "Cargo.lock",
            "proof/browser",
            "fabrication",
            "products",

            "semantics",
            "site",
            "targets/avr",
            "targets/browser",
            "targets/conduitos",
            "targets/esp32",
            "targets/orange-pi",
            "targets/raspberry-pi",
            "targets/std",
        ],
        // Fingerprint complete owning domains so a trusted controller can
        // validate a candidate that renames proof, staging, or workflow files.
        // Paths and bytes remain hashed; renames invalidate prior receipts.
        implementation_inputs: &["proof/browser", "proof/ci", "tools/ci", "tools", "proof/browser/package.json", "proof/browser/package-lock.json", "targets/browser/tools", "products/tour/tools", "products/creche/tools", "products/patchbay/tools", "site/tools", ".github/workflows"],
        consumed_artifacts: &[],
        environment: "pages-carrier-v1",
        applicability: Applicability::CandidateAndIntegration,
        selection: Selection::PagesProducts,
        command: "workflow:tour-and-creche-products/pages-carrier",
    },
    ProofSpec {
        id: "repository.standalone-locks",
        contract_version: 1,
        kind: ProofKind::Machine,
        inputs: &["Cargo.toml", "Cargo.lock", "targets/esp32"],
        implementation_inputs: &[
            "tools/xtask/src/commands/ci/standalone_locks.rs",
            "tools",
            ".github/workflows/check.yml",
        ],
        consumed_artifacts: &[],
        environment: "ubuntu-rust-1.98.1-v1",
        applicability: Applicability::CandidateAndIntegration,
        selection: Selection::Esp32Required,
        command: "cargo xtask ci standalone-locks --locked",
    },
    ProofSpec {
        id: "machine.esp32-wroom",
        contract_version: 1,
        kind: ProofKind::Machine,
        inputs: &["Cargo.toml", "Cargo.lock", "architecture", "fabrication", "semantics", "targets/esp32"],
        implementation_inputs: &["tools/xtask/src/commands/esp32_firmware.rs", "tools", ".github/workflows/check.yml"],
        consumed_artifacts: &[],
        environment: "ubuntu-rust-1.91.1-xtensa-esp32-v1",
        applicability: Applicability::CandidateAndIntegration,
        selection: Selection::Esp32Target("wroom"),
        command: "cargo xtask esp32-firmware build --target wroom --locked",
    },
    ProofSpec {
        id: "machine.esp32-s3",
        contract_version: 1,
        kind: ProofKind::Machine,
        inputs: &["Cargo.toml", "Cargo.lock", "architecture", "fabrication", "semantics", "targets/esp32"],
        implementation_inputs: &["tools/xtask/src/commands/esp32_firmware.rs", "tools", ".github/workflows/check.yml"],
        consumed_artifacts: &[],
        environment: "ubuntu-rust-1.91.1-xtensa-esp32s3-v1",
        applicability: Applicability::CandidateAndIntegration,
        selection: Selection::Esp32Target("s3"),
        command: "cargo xtask esp32-firmware build --target s3 --locked",
    },
    ProofSpec {
        id: "machine.esp32-c3",
        contract_version: 1,
        kind: ProofKind::Machine,
        inputs: &[
            "Cargo.toml",
            "Cargo.lock",
            "architecture",
            "fabrication",
            "semantics",
            "targets/esp32",
        ],
        implementation_inputs: &[
            "tools/xtask/src/commands/esp32_firmware.rs", "tools",
            ".github/workflows/check.yml",
        ],
        consumed_artifacts: &[],
        environment: "ubuntu-rust-1.91.1-riscv32imc-v1",
        applicability: Applicability::CandidateAndIntegration,
        selection: Selection::Esp32Target("c3"),
        command: "cargo xtask esp32-firmware build --target c3 --locked",
    },
    ProofSpec {
        id: "conduitos.limine",
        contract_version: 1,
        kind: ProofKind::Machine,
        inputs: &["targets/conduitos/fabrication/xtask/profile.rs"],
        implementation_inputs: &[".github/workflows/check.yml"],
        consumed_artifacts: &[],
        environment: "ubuntu-conduitos-limine-v1",
        applicability: Applicability::CandidateAndIntegration,
        selection: Selection::ConduitosRequired,
        command: "restore or fetch the pinned Limine archive, then verify its SHA-256 digest",
    },
    ProofSpec {
        id: "conduitos.tools",
        contract_version: 1,
        kind: ProofKind::Machine,
        inputs: &["targets/conduitos"],
        implementation_inputs: &["targets/conduitos/tools/conduitos-tools.sh", "targets/conduitos/tools/conduitos-tools-packages.txt", "targets/conduitos/tools", ".github/workflows/check.yml"],
        consumed_artifacts: &[],
        environment: "ubuntu-conduitos-tools-v1",
        applicability: Applicability::CandidateAndIntegration,
        selection: Selection::ConduitosRequired,
        command: "targets/conduitos/tools/conduitos-tools.sh prepare target/conduitos/tool-bundle && targets/conduitos/tools/conduitos-tools.sh verify target/conduitos/tool-bundle",
    },
    conduitos_proof!("conduitos.x86.kernel", Selection::ConduitosX86("kernel"), "ubuntu-qemu-x86_64-batch-v1", "cargo xtask conduitos prove-many --proof kernel --locked"),
    conduitos_proof!("conduitos.x86.xhci", Selection::ConduitosX86("xhci"), "ubuntu-qemu-x86_64-batch-v1", "cargo xtask conduitos prove-many --proof xhci --locked"),
    conduitos_proof!("conduitos.x86.usb", Selection::ConduitosX86("usb"), "ubuntu-qemu-x86_64-batch-v1", "cargo xtask conduitos prove-many --proof usb --locked"),
    conduitos_proof!("conduitos.x86.hid", Selection::ConduitosX86("hid"), "ubuntu-qemu-x86_64-batch-v1", "cargo xtask conduitos prove-many --proof hid --locked"),
    conduitos_proof!("conduitos.x86.keyboard", Selection::ConduitosX86("keyboard"), "ubuntu-qemu-x86_64-batch-v1", "cargo xtask conduitos prove-many --proof keyboard --locked"),
    conduitos_proof!("conduitos.x86.front-door", Selection::ConduitosX86("front-door"), "ubuntu-qemu-x86_64-batch-v1", "cargo xtask conduitos prove-many --proof front-door --locked"),
    conduitos_proof!("conduitos.x86.product-journey", Selection::ConduitosX86("product-journey"), "ubuntu-qemu-x86_64-batch-v1", "cargo xtask conduitos prove-many --proof product-journey --locked"),
    conduitos_proof!("conduitos.x86.rescue", Selection::ConduitosX86("rescue"), "ubuntu-qemu-x86_64-batch-v1", "cargo xtask conduitos prove-many --proof rescue --locked"),
    conduitos_proof!("conduitos.architecture.aarch64", Selection::ConduitosArchitecture("aarch64"), "ubuntu-qemu-aarch64-v1", "cargo xtask conduitos prove --arch aarch64 --locked"),
    conduitos_proof!("conduitos.architecture.ia32", Selection::ConduitosArchitecture("ia32"), "ubuntu-qemu-ia32-v1", "cargo xtask conduitos architecture-matrix --locked && cargo xtask conduitos prove --arch ia32 --locked"),
    conduitos_proof!("conduitos.architecture.riscv64", Selection::ConduitosArchitecture("riscv64"), "ubuntu-qemu-riscv64-v1", "cargo xtask conduitos prove --arch riscv64 --locked"),
    conduitos_proof!("conduitos.architecture.loongarch64", Selection::ConduitosArchitecture("loongarch64"), "ubuntu-qemu-loongarch64-v1", "cargo xtask conduitos prove --arch loongarch64 --locked"),
    conduitos_proof!("conduitos.aarch64-product", Selection::ConduitosAarch64Product, "ubuntu-qemu-aarch64-product-v1", "cargo xtask host build targets/conduitos/profiles/conduitos-aarch64-headless.profile.json --locked"),
];
