use crate::{process::Step, proof::ProofClass};

/// Authoritative definition of the normal Rust workspace check gate.
pub const WORKSPACE_STEPS: &[Step] = &[
    Step::new(
        "check.fmt",
        "Check formatting across workspace",
        "cargo",
        &["fmt", "--all", "--check"],
    ),
    Step::new(
        "check.clippy",
        "Clippy warnings check across workspace",
        "cargo",
        &[
            "clippy",
            "--workspace",
            "--all-targets",
            "--",
            "-D",
            "warnings",
        ],
    ),
    Step::new(
        "check.test",
        "Workspace unit and integration tests",
        "cargo",
        &["test", "--workspace"],
    ),
    Step::new(
        "check.kernel-alloc",
        "Kernel alloc feature tests",
        "cargo",
        &["test", "-p", "conduit-kernel", "--features", "alloc"],
    ),
    Step::new(
        "check.system-continuity",
        "Durable system continuity conformance",
        "cargo",
        &["test", "-p", "conduit-system-continuity"],
    ),
    Step::new(
        "check.no-std.kernel",
        "Kernel no-default-features check",
        "cargo",
        &["check", "-p", "conduit-kernel", "--no-default-features"],
    ),
    Step::new(
        "check.no-std.chat",
        "Portable chat and messaging no-default-features check",
        "cargo",
        &["check", "-p", "conduit-chat", "--no-default-features"],
    ),
    Step::new(
        "check.no-std.data",
        "Structured-data semantics no-default-features check",
        "cargo",
        &["check", "-p", "conduit-data", "--no-default-features"],
    ),
    Step::new(
        "check.no-std.language",
        "Language semantics no-default-features check",
        "cargo",
        &["check", "-p", "conduit-language", "--no-default-features"],
    ),
    Step::new(
        "check.no-std.signal",
        "Signal no-default-features check",
        "cargo",
        &["check", "-p", "conduit-signal", "--no-default-features"],
    ),
    Step::new(
        "check.no-std.wire",
        "Wire no-default-features check",
        "cargo",
        &["check", "-p", "conduit-wire", "--no-default-features"],
    ),
    Step::new(
        "check.no-std.semantic-catalog",
        "semantic-catalog no-default-features check",
        "cargo",
        &[
            "check",
            "-p",
            "conduit-semantic-catalog",
            "--no-default-features",
        ],
    ),
    Step::new(
        "check.no-std.presentation",
        "Portable presentation no-default-features check",
        "cargo",
        &[
            "check",
            "-p",
            "conduit-presentation",
            "--no-default-features",
        ],
    ),
    Step::new(
        "check.no-std.extracted-domains",
        "Extracted human, robotics, JSON, and Patchbay control no-default-features check",
        "cargo",
        &[
            "check",
            "-p",
            "conduit-human",
            "-p",
            "conduit-robotics",
            "-p",
            "conduit-web",
            "-p",
            "patchbay-control",
            "--no-default-features",
        ],
    ),
    Step::new(
        "check.no-std.std-host",
        "std-host no-default-features check",
        "cargo",
        &["check", "-p", "conduit-std-host", "--no-default-features"],
    ),
    Step::typed(
        "check.thumb.chat",
        "Portable chat and messaging Thumb target check",
        "cargo",
        &[
            "check",
            "-p",
            "conduit-chat",
            "--target",
            "thumbv6m-none-eabi",
        ],
        None,
        Some("thumbv6m-none-eabi"),
        Some(ProofClass::ContractCompile),
        &[],
    ),
    Step::typed(
        "check.thumb.data",
        "Structured-data semantics Thumb target check",
        "cargo",
        &[
            "check",
            "-p",
            "conduit-data",
            "--target",
            "thumbv6m-none-eabi",
        ],
        None,
        Some("thumbv6m-none-eabi"),
        Some(ProofClass::ContractCompile),
        &[],
    ),
    Step::typed(
        "check.thumb.language",
        "Language semantics Thumb target check",
        "cargo",
        &[
            "check",
            "-p",
            "conduit-language",
            "--target",
            "thumbv6m-none-eabi",
        ],
        None,
        Some("thumbv6m-none-eabi"),
        Some(ProofClass::ContractCompile),
        &[],
    ),
    Step::typed(
        "check.thumb.system-continuity",
        "Durable system continuity Thumb target check",
        "cargo",
        &[
            "check",
            "-p",
            "conduit-system-continuity",
            "--target",
            "thumbv6m-none-eabi",
        ],
        None,
        Some("thumbv6m-none-eabi"),
        Some(ProofClass::ContractCompile),
        &[],
    ),
    Step::typed(
        "check.thumb.extracted-domains",
        "Extracted human, robotics, JSON, and Patchbay control Thumb target check",
        "cargo",
        &[
            "check",
            "-p",
            "conduit-human",
            "-p",
            "conduit-robotics",
            "-p",
            "conduit-web",
            "-p",
            "patchbay-control",
            "--no-default-features",
            "--target",
            "thumbv6m-none-eabi",
        ],
        None,
        Some("thumbv6m-none-eabi"),
        Some(ProofClass::ContractCompile),
        &[],
    ),
    Step::typed(
        "check.wasm.browser-runtime",
        "Browser runtime WASM target check",
        "cargo",
        &[
            "check",
            "-p",
            "conduit-browser-runtime",
            "--target",
            "wasm32-unknown-unknown",
        ],
        None,
        Some("wasm32-unknown-unknown"),
        Some(ProofClass::ContractCompile),
        &[],
    ),
    Step::typed(
        "check.wasm.wire",
        "Wire WASM session corpus check",
        "cargo",
        &[
            "check",
            "-p",
            "conduit-wire",
            "--target",
            "wasm32-unknown-unknown",
            "--test",
            "session_wire_corpus",
        ],
        None,
        Some("wasm32-unknown-unknown"),
        Some(ProofClass::ContractCompile),
        &[],
    ),
    Step::typed(
        "check.thumb.kernel",
        "Kernel thumb target check",
        "cargo",
        &[
            "check",
            "-p",
            "conduit-kernel",
            "--target",
            "thumbv6m-none-eabi",
        ],
        None,
        Some("thumbv6m-none-eabi"),
        Some(ProofClass::ContractCompile),
        &[],
    ),
    Step::typed(
        "check.thumb.create-oi",
        "Create OI mechanism thumb target check",
        "cargo",
        &[
            "check",
            "-p",
            "conduit-create-oi",
            "--target",
            "thumbv6m-none-eabi",
        ],
        None,
        Some("thumbv6m-none-eabi"),
        Some(ProofClass::ContractCompile),
        &[],
    ),
    Step::typed(
        "check.thumb.core",
        "Core thumb target check",
        "cargo",
        &[
            "check",
            "-p",
            "conduit-core",
            "--target",
            "thumbv6m-none-eabi",
        ],
        None,
        Some("thumbv6m-none-eabi"),
        Some(ProofClass::ContractCompile),
        &[],
    ),
    Step::typed(
        "check.thumb.body",
        "Body lifecycle thumb target check",
        "cargo",
        &[
            "check",
            "-p",
            "conduit-body",
            "--target",
            "thumbv6m-none-eabi",
        ],
        None,
        Some("thumbv6m-none-eabi"),
        Some(ProofClass::ContractCompile),
        &[],
    ),
    Step::typed(
        "check.thumb.observatory",
        "Observatory thumb target check",
        "cargo",
        &[
            "check",
            "-p",
            "conduit-observatory",
            "--target",
            "thumbv6m-none-eabi",
        ],
        None,
        Some("thumbv6m-none-eabi"),
        Some(ProofClass::ContractCompile),
        &[],
    ),
    Step::typed(
        "check.thumb.semantic-catalog",
        "semantic-catalog thumb target check",
        "cargo",
        &[
            "check",
            "-p",
            "conduit-semantic-catalog",
            "--no-default-features",
            "--target",
            "thumbv6m-none-eabi",
        ],
        None,
        Some("thumbv6m-none-eabi"),
        Some(ProofClass::ContractCompile),
        &[],
    ),
    Step::typed(
        "check.thumb.presentation",
        "Portable presentation Thumb target check",
        "cargo",
        &[
            "check",
            "-p",
            "conduit-presentation",
            "--no-default-features",
            "--target",
            "thumbv6m-none-eabi",
        ],
        None,
        Some("thumbv6m-none-eabi"),
        Some(ProofClass::ContractCompile),
        &[],
    ),
    Step::new(
        "check.pico-local.dry-run",
        "Dry-run verify of Pico W receipts",
        "cargo",
        &["xtask", "pico", "verify", "--dry-run"],
    ),
    Step::new(
        "check.std-pico-usb.dry-run",
        "Dry-run verify of std-to-Pico USB-CDC remote session proof",
        "cargo",
        &["xtask", "prove", "std-pico-usb", "--dry-run"],
    ),
    Step::new(
        "check.pico-wifi-bootstrap.dry-run",
        "Dry-run verify of the USB-authorized Pico W Wi-Fi proof",
        "cargo",
        &[
            "xtask",
            "prove",
            "pico-wifi-bootstrap",
            "--ssid-env",
            "CONDUIT_TEST_WIFI_SSID",
            "--credential-env",
            "CONDUIT_TEST_WIFI_CREDENTIAL",
            "--dry-run",
        ],
    ),
    Step::new(
        "check.pico-appliance.dry-run",
        "Dry-run verify of the physical Pico W AP/DHCP/DNS/HTTP Hello proof",
        "cargo",
        &[
            "xtask",
            "prove",
            "pico-appliance",
            "--client-interface",
            "wlan-proof-fixture",
            "--dry-run",
        ],
    ),
    Step::new(
        "check.pico-appliance-hil.dry-run",
        "Dry-run verify of the exact two-Pico AP/DHCP/DNS/HTTP Hello proof",
        "cargo",
        &[
            "xtask",
            "prove",
            "pico-appliance-hil",
            "--link-port",
            "appliance-link-fixture",
            "--sign-port",
            "appliance-sign-fixture",
            "--client-link-port",
            "client-link-fixture",
            "--dry-run",
        ],
    ),
    Step::new(
        "check.r1-new-plan-recovery-hil.dry-run",
        "Dry-run verify of the physical R1 WebSocket-to-USB new-Plan proof",
        "cargo",
        &[
            "xtask",
            "prove",
            "r1-new-plan-recovery-hil",
            "--interactive",
            "--ssid-env",
            "CONDUIT_TEST_WIFI_SSID",
            "--credential-env",
            "CONDUIT_TEST_WIFI_CREDENTIAL",
            "--dry-run",
        ],
    ),
    Step::new(
        "check.r1-plan-c-continuation-hil.dry-run",
        "Dry-run verify of the physical R1 same-Plan Line continuation proof",
        "cargo",
        &[
            "xtask",
            "prove",
            "r1-plan-c-continuation-hil",
            "--interactive",
            "--ssid-env",
            "CONDUIT_TEST_WIFI_SSID",
            "--credential-env",
            "CONDUIT_TEST_WIFI_CREDENTIAL",
            "--dry-run",
        ],
    ),
    Step::new(
        "check.r1-hil.dry-run",
        "Dry-run verify of the combined one-Body physical R1 proof",
        "cargo",
        &[
            "xtask",
            "prove",
            "r1-hil",
            "--interactive",
            "--ssid-env",
            "CONDUIT_TEST_WIFI_SSID",
            "--credential-env",
            "CONDUIT_TEST_WIFI_CREDENTIAL",
            "--dry-run",
        ],
    ),
];

pub const KERNEL_TAKEOVER_STEPS: &[Step] = &[
    Step::new(
        "check.kernel.std-host-no-default",
        "check std-host no-default-features",
        "cargo",
        &["check", "-p", "conduit-std-host", "--no-default-features"],
    ),
    Step::new(
        "check.kernel.lowering",
        "test exact_signal_fragment_lowers_to_numeric_kernel_tables",
        "cargo",
        &[
            "test",
            "-p",
            "conduit-std-host",
            "exact_signal_fragment_lowers_to_numeric_kernel_tables",
        ],
    ),
    Step::new(
        "check.kernel.streamed",
        "test streamed_output_uses_a_virtual_clock_and_retains_terminal_sign",
        "cargo",
        &[
            "test",
            "-p",
            "conduit-std-host",
            "streamed_output_uses_a_virtual_clock_and_retains_terminal_sign",
        ],
    ),
    Step::new(
        "check.kernel.three-sink",
        "test local_three_sink_signal_fanout_uses_only_the_sealed_kernel_profile",
        "cargo",
        &[
            "test",
            "-p",
            "conduit-std-host",
            "local_three_sink_signal_fanout_uses_only_the_sealed_kernel_profile",
        ],
    ),
    Step::new(
        "check.kernel.unsupported",
        "test unsupported_production_std_form_fails_closed_without_a_legacy_pump",
        "cargo",
        &[
            "test",
            "-p",
            "conduit-std-host",
            "unsupported_production_std_form_fails_closed_without_a_legacy_pump",
        ],
    ),
    Step::new(
        "check.kernel.multivalue",
        "test kernel_multivalue",
        "cargo",
        &["test", "-p", "conduit-std-host", "kernel_multivalue"],
    ),
    Step::new(
        "check.kernel.preparation",
        "test kernel_preparation",
        "cargo",
        &["test", "-p", "conduit-std-host", "kernel_preparation"],
    ),
    Step::new(
        "check.kernel.browser-drawbridge",
        "test current_hosts_depend_only_on_exact_lowering_and_kernel_execution",
        "cargo",
        &[
            "test",
            "-p",
            "conduit-plan-lowering",
            "--test",
            "lowering_boundary",
            "current_hosts_depend_only_on_exact_lowering_and_kernel_execution",
        ],
    ),
    Step::new(
        "check.kernel.hello-multi-value",
        "test typed_multi_value_form_runs_through_the_std_kernel",
        "cargo",
        &[
            "test",
            "-p",
            "conduit",
            "--test",
            "hello",
            "typed_multi_value_form_runs_through_the_std_kernel",
        ],
    ),
    Step::new(
        "check.kernel.sink-no-output",
        "test admitted_sink_host_operation_may_have_no_output_payload",
        "cargo",
        &[
            "test",
            "-p",
            "conduit-kernel",
            "admitted_sink_host_operation_may_have_no_output_payload",
        ],
    ),
    Step::typed(
        "check.kernel.thumb",
        "check kernel thumb",
        "cargo",
        &[
            "check",
            "-p",
            "conduit-kernel",
            "--target",
            "thumbv6m-none-eabi",
        ],
        None,
        Some("thumbv6m-none-eabi"),
        Some(ProofClass::ContractCompile),
        &[],
    ),
    Step::typed(
        "check.kernel.core-thumb",
        "check core thumb",
        "cargo",
        &[
            "check",
            "-p",
            "conduit-core",
            "--target",
            "thumbv6m-none-eabi",
        ],
        None,
        Some("thumbv6m-none-eabi"),
        Some(ProofClass::ContractCompile),
        &[],
    ),
];

pub const PLANNING_S2_STEPS: &[Step] = &[
    Step::new(
        "check.planning.identity-binds",
        "test checked_form_identity_binds_contract_revision_and_ports",
        "cargo",
        &[
            "test",
            "-p",
            "conduit-form",
            "checked_form_identity_binds_contract_revision_and_ports",
        ],
    ),
    Step::new(
        "check.planning.source-checked-expanded",
        "test source_checked_and_expanded_form_identities_stay_distinct",
        "cargo",
        &[
            "test",
            "-p",
            "conduit-form",
            "source_checked_and_expanded_form_identities_stay_distinct",
        ],
    ),
    Step::new(
        "check.planning.planner",
        "test planning tests",
        "cargo",
        &["test", "-p", "conduit-planner", "planning_"],
    ),
    Step::new(
        "check.planning.kernel-admission",
        "test exact kernel admission, authority, pressure, cancellation, and Sign contracts",
        "cargo",
        &["test", "-p", "conduit-kernel"],
    ),
    Step::typed(
        "check.planning.core-thumb",
        "check core thumb",
        "cargo",
        &[
            "check",
            "-p",
            "conduit-core",
            "--target",
            "thumbv6m-none-eabi",
        ],
        None,
        Some("thumbv6m-none-eabi"),
        Some(ProofClass::ContractCompile),
        &[],
    ),
];

pub const FORM_S3_STEPS: &[Step] = &[
    Step::new("check.form.lossless-doc", "test lossless_document_", "cargo", &["test", "-p", "conduit-form", "lossless_document_"]),
    Step::new("check.form.missing-close", "test missing_close_is_diagnosed_at_eof_without_losing_source", "cargo", &["test", "-p", "conduit-form", "missing_close_is_diagnosed_at_eof_without_losing_source"]),
    Step::new("check.form.source-checked-expanded", "test source_checked_and_expanded_form_identities_stay_distinct", "cargo", &["test", "-p", "conduit-form", "source_checked_and_expanded_form_identities_stay_distinct"]),
    Step::new("check.form.checked-export-parent-kind", "test checked_export_is_the_only_source_of_a_parent_kind_boundary", "cargo", &["test", "-p", "conduit-form", "checked_export_is_the_only_source_of_a_parent_kind_boundary"]),
    Step::new("check.form.duplicate-export-rejected", "test duplicate_export_capabilities_are_rejected", "cargo", &["test", "-p", "conduit-form", "duplicate_export_capabilities_are_rejected"]),
    Step::new("check.form.multiple-typed-faces", "test multiple_typed_and_zero_sided_faces_check_as_ordinary_kinds", "cargo", &["test", "-p", "conduit-form", "multiple_typed_and_zero_sided_faces_check_as_ordinary_kinds"]),
    Step::new("check.form.face-mutations-fail-closed", "test checked_face_mutations_fail_closed", "cargo", &["test", "-p", "conduit-form", "checked_face_mutations_fail_closed"]),
    Step::new("check.form.inline-nested-checked", "test inline_nested_form_uses_the_same_checked_boundary_as_a_standalone_form", "cargo", &["test", "-p", "conduit-form", "inline_nested_form_uses_the_same_checked_boundary_as_a_standalone_form"]),
    Step::new("check.form.parent-expanded-identity", "test parent_expanded_identity_binds_hidden_child_semantics_not_checked_boundary", "cargo", &["test", "-p", "conduit-form", "parent_expanded_identity_binds_hidden_child_semantics_not_checked_boundary"]),
    Step::new("check.form.nested-expansion-paths", "test nested_expansion_paths_are_canonical_and_substitution_fails_closed", "cargo", &["test", "-p", "conduit-form", "nested_expansion_paths_are_canonical_and_substitution_fails_closed"]),
    Step::new("check.form.nested-errors-span", "test nested_errors_keep_the_outer_document_and_exact_inner_span", "cargo", &["test", "-p", "conduit-form", "nested_errors_keep_the_outer_document_and_exact_inner_span"]),
    Step::new("check.form.inline-depth-ceiling", "test inline_nesting_has_a_hard_depth_ceiling", "cargo", &["test", "-p", "conduit-form", "inline_nesting_has_a_hard_depth_ceiling"]),
    Step::new("check.form.composite-authored-parent", "test authored_parent_consumes_derived_export_through_an_ordinary_planned_cord", "cargo", &["test", "-p", "conduit-composite", "authored_parent_consumes_derived_export_through_an_ordinary_planned_cord"]),
    Step::new("check.form.composite-multi-kind", "test two_input_two_output_multi_kind_faces_execute_with_exact_pressure_and_closure", "cargo", &["test", "-p", "conduit-composite", "two_input_two_output_multi_kind_faces_execute_with_exact_pressure_and_closure"]),
    Step::new("check.form.composite-input-output-only", "test input_only_and_output_only_exports_plan_as_ordinary_operations", "cargo", &["test", "-p", "conduit-composite", "input_only_and_output_only_exports_plan_as_ordinary_operations"]),
    Step::new("check.form.composite-face-mapping-mutation", "test composite_definition_rejects_every_face_mapping_mutation", "cargo", &["test", "-p", "conduit-composite", "composite_definition_rejects_every_face_mapping_mutation"]),
    Step::new("check.form.composite-terminal-failure", "test named_face_delivery_failure_and_cancellation_are_parent_terminal_without_topology_leaks", "cargo", &["test", "-p", "conduit-composite", "named_face_delivery_failure_and_cancellation_are_parent_terminal_without_topology_leaks"]),
    Step::new("check.form.execution-identity-chain", "test execution_identity_chain_keeps_plan_play_sign_and_presentation_distinct", "cargo", &["test", "-p", "conduit-core", "execution_identity_chain_keeps_plan_play_sign_and_presentation_distinct"]),
    Step::new("check.form.observatory-current-plan", "test projects exact current Plan truth", "cargo", &["test", "-p", "conduit-observatory", "projects_exact_std_pico_usb_arrangement_without_promoting_physical_proof"]),
];

pub const BROWSER_CHECK_STEPS: &[Step] = &[
    Step::new(
        "check.browser.browser-runtime",
        "test conduit-browser-runtime",
        "cargo",
        &["test", "-p", "conduit-browser-runtime"],
    ),
    Step::new(
        "check.browser.host-operations",
        "Prove finite generic browser Host operations and negative outcomes",
        "node",
        &["--test", "proof/browser/browser-host-operations.test.mjs"],
    ),
    Step::typed(
        "check.browser.wasm-build",
        "Build conduit-browser-runtime WASM",
        "cargo",
        &[
            "build",
            "-p",
            "conduit-browser-runtime",
            "--target",
            "wasm32-unknown-unknown",
            "--release",
        ],
        None,
        Some("wasm32-unknown-unknown"),
        Some(ProofClass::ContractCompile),
        &[],
    ),
    Step::new(
        "check.browser.host-entrance-build",
        "Build the standalone browser Host entrance",
        "cargo",
        &["build", "-p", "conduit-browser-host"],
    ),
    Step::new(
        "check.browser.webchat-server-build",
        "Build bounded WebSocket chat server",
        "cargo",
        &["build", "-p", "conduit-std-host", "--bin", "webchat-server"],
    ),
    Step::new(
        "check.browser.pool-webchat-server-build",
        "Build bounded shared-pool chat server",
        "cargo",
        &[
            "build",
            "-p",
            "conduit-std-host",
            "--bin",
            "pool-webchat-server",
        ],
    ),
    Step::new(
        "check.browser.r1-three-peer-input-server-build",
        "Build bounded R1 three-peer input server",
        "cargo",
        &[
            "build",
            "-p",
            "conduit-std-host",
            "--bin",
            "r1-three-peer-input-server",
        ],
    ),
    Step::new(
        "check.browser.patchbay-native-build",
        "Build native Patchbay distributed source",
        "cargo",
        &["build", "-p", "patchbay-native"],
    ),
    Step::typed(
        "check.browser.host-proof",
        "Run browser host test proof",
        "npm",
        &["--prefix", "proof/browser", "run", "test:browser-host"],
        None,
        Some("playwright"),
        Some(ProofClass::LiveBrowser),
        &[],
    ),
];

pub const OBSERVATORY_READINESS_STEPS: &[Step] = &[
    Step::new(
        "check.observatory.test",
        "test conduit-observatory",
        "cargo",
        &["test", "-p", "conduit-observatory"],
    ),
    Step::typed(
        "check.observatory.thumb",
        "check conduit-observatory thumb target",
        "cargo",
        &[
            "check",
            "-p",
            "conduit-observatory",
            "--target",
            "thumbv6m-none-eabi",
        ],
        None,
        Some("thumbv6m-none-eabi"),
        Some(ProofClass::ContractCompile),
        &[],
    ),
];

pub const SEMANTIC_CATALOG_READINESS_STEPS: &[Step] = &[
    Step::new(
        "check.semantic-catalog.test",
        "test conduit-semantic-catalog",
        "cargo",
        &["test", "-p", "conduit-semantic-catalog"],
    ),
    Step::typed(
        "check.semantic-catalog.thumb",
        "check conduit-semantic-catalog thumb target",
        "cargo",
        &[
            "check",
            "-p",
            "conduit-semantic-catalog",
            "--no-default-features",
            "--target",
            "thumbv6m-none-eabi",
        ],
        None,
        Some("thumbv6m-none-eabi"),
        Some(ProofClass::ContractCompile),
        &[],
    ),
];

/// Deterministic K5/K5b contracts plus K8's two truthful platform seams.
pub const INPUT_SEMANTICS_STEPS: &[Step] = &[
    Step::new(
        "check.input-semantics.core",
        "test the reusable keymap and chord contracts",
        "cargo",
        &["test", "-p", "conduit-core", "--test", "input_semantics"],
    ),
    Step::new(
        "check.input-semantics.std-host",
        "test ordinary std Host input Forms and bounded operations",
        "cargo",
        &["test", "-p", "conduit-std-host", "input_semantics"],
    ),
    Step::new(
        "check.input-semantics.patchbay",
        "test finite Patchbay input controls",
        "cargo",
        &["test", "-p", "patchbay-model", "input_semantic_controls"],
    ),
    Step::new(
        "check.input-semantics.conduitos-peer-vectors",
        "test ConduitOS USB conversion against shared peer vectors",
        "cargo",
        &[
            "test",
            "-p",
            "conduitos",
            "keyboard_bridge::tests::usb_bridge_matches_every_shared_peer_conformance_value",
        ],
    ),
    Step::new(
        "check.input-semantics.native-peer",
        "test native physical-key mapping, shared semantics, planning, and finite failures",
        "cargo",
        &["test", "-p", "patchbay-native", "portable_keyboard_tests"],
    ),
    Step::typed(
        "check.input-semantics.thumb",
        "check reusable input contracts for the thumb target",
        "cargo",
        &[
            "check",
            "-p",
            "conduit-core",
            "-p",
            "conduit-semantic-catalog",
            "--no-default-features",
            "--target",
            "thumbv6m-none-eabi",
        ],
        None,
        Some("thumbv6m-none-eabi"),
        Some(ProofClass::ContractCompile),
        &[],
    ),
];

pub const SIM_READINESS_STEPS: &[Step] = &[
    Step::new(
        "check.sim.signal-no-default",
        "check conduit-signal no-default-features",
        "cargo",
        &["check", "-p", "conduit-signal", "--no-default-features"],
    ),
    Step::new(
        "check.sim.wire-no-default",
        "check conduit-wire no-default-features",
        "cargo",
        &["check", "-p", "conduit-wire", "--no-default-features"],
    ),
    Step::new(
        "check.sim.wire-test",
        "test conduit-wire",
        "cargo",
        &["test", "-p", "conduit-wire"],
    ),
];
