use crate::{process::Step, proof::ProofClass};

pub const PROVE_PATCHBAY_BODY_WORKBENCH_STEPS: &[Step] = &[
    Step::typed(
        "prove.patchbay-body-workbench.shared-model",
        "Prove bounded Body attachment, current frame, biography, and negative replacement contracts",
        "cargo",
        &["test", "-p", "patchbay-model"],
        None,
        None,
        Some(ProofClass::DeterministicUnit),
        &[],
    ),
    Step::typed(
        "prove.patchbay-body-workbench.artifacts",
        "Build the HTML, native, and bounded identity-ledger capstone artifacts",
        "cargo",
        &[
            "build", "-p", "patchbay-html", "--bin", "patchbay-html", "--bin",
            "patchbay-body-workbench-proof", "-p", "patchbay-native", "--bin",
            "patchbay-native",
        ],
        None,
        None,
        Some(ProofClass::ContractCompile),
        &[
            "target/debug/patchbay-html",
            "target/debug/patchbay-native",
            "target/debug/patchbay-body-workbench-proof",
        ],
    ),
    Step::typed(
        "prove.patchbay-body-workbench.identity-ledger",
        "Generate and validate the finite cross-manifestation Body identity ledger",
        "target/debug/patchbay-body-workbench-proof",
        &["target/conduit-evidence/patchbay-body-workbench/identity-ledger.json"],
        None,
        None,
        Some(ProofClass::HostedIntegration),
        &["target/conduit-evidence/patchbay-body-workbench/identity-ledger.json"],
    ),
    Step::typed(
        "prove.patchbay-body-workbench.html",
        "Prove HTML attachment, exact evidence retention, and semantic workbench composition",
        "cargo",
        &["test", "-p", "patchbay-html"],
        None,
        None,
        Some(ProofClass::HostedIntegration),
        &[],
    ),
    Step::typed(
        "prove.patchbay-body-workbench.native",
        "Prove native Program, Body, History, Exact, Linear, and action composition deterministically",
        "cargo",
        &["test", "-p", "patchbay-native", "--all-targets"],
        None,
        None,
        Some(ProofClass::HostedIntegration),
        &[],
    ),
    Step::typed(
        "prove.patchbay-body-workbench.browser",
        "Prove hosted/external Body workbenches and exact Program-to-Body Follow in pinned Chromium",
        "npx",
        &[
            "playwright",
            "test",
            "--config",
            "proof/browser/patchbay-html.playwright.config.mjs",
            "proof/browser/patchbay-body-workbench.spec.mjs",
            "proof/browser/patchbay-follow.spec.mjs",
        ],
        None,
        Some("playwright"),
        Some(ProofClass::LiveBrowser),
        &[],
    ),
];
