use crate::{process::Step, proof::ProofClass};

pub const PROVE_PATCHBAY_BODY_WORKBENCH_STEPS: &[Step] = &[
    Step::typed(
        "prove.patchbay-body-workbench.authoring-contracts",
        "Prove canonical catalog, compatibility and shared diagram facts",
        "cargo",
        &["test", "-p", "conduit-semantic-catalog", "-p", "patchbay-graph", "-p", "patchbay-svg-mask"],
        None,
        None,
        Some(ProofClass::DeterministicUnit),
        &[],
    ),
    Step::typed(
        "prove.patchbay-body-workbench.workspace-contract",
        "Prove portable workspace bounds, migration and semantic separation",
        "cargo",
        &["test", "-p", "patchbay-application", "workspace"],
        None,
        None,
        Some(ProofClass::DeterministicUnit),
        &[],
    ),
    Step::typed(
        "prove.patchbay-body-workbench.workspace-consumer",
        "Prove browser workspace schema and live-overlay separation",
        "node",
        &["--test", "proof/browser/patchbay-workspace.test.mjs", "proof/browser/patchbay-authoring-contracts.test.mjs"],
        None,
        None,
        Some(ProofClass::DeterministicUnit),
        &[],
    ),
    Step::typed(
        "prove.patchbay-body-workbench.workspace-renderer",
        "Prove durable presentation-only layouts and canonical highlighting in Chromium",
        "node",
        &["--test", "proof/browser/patchbay-workspace-render.test.mjs"],
        None,
        Some("playwright"),
        Some(ProofClass::LiveBrowser),
        &[],
    ),
    Step::typed(
        "prove.patchbay-body-workbench.browser-runtime",
        "Build the exact browser WASM used by the page Body execution proof",
        "cargo",
        &["build", "-p", "conduit-browser-runtime", "--target", "wasm32-unknown-unknown", "--release"],
        None,
        None,
        Some(ProofClass::ContractCompile),
        &["target/wasm32-unknown-unknown/release/conduit_browser_runtime.wasm"],
    ),
    Step::typed(
        "prove.patchbay-body-workbench.shared-model",
        "Prove bounded Body attachment, current frame, biography, and negative replacement contracts",
        "cargo",
        &["test", "-p", "conduit-patchbay-workbench"],
        None,
        None,
        Some(ProofClass::DeterministicUnit),
        &[],
    ),
    Step::typed(
        "prove.patchbay-body-workbench.artifacts",
        "Build the HTML, native, and bounded identity-ledger capstone artifacts",
        "cargo",
        &[
            "build", "-p", "conduit-browser-patchbay-workbench", "--bin", "conduit-browser-patchbay-workbench", "--bin",
            "patchbay-body-workbench-proof", "-p", "patchbay-native", "--bin",
            "patchbay-native", "-p", "conduit-std-host", "--bin", "browser-admission-probe",
        ],
        None,
        None,
        Some(ProofClass::ContractCompile),
        &[
            "target/debug/conduit-browser-patchbay-workbench",
            "target/debug/patchbay-native",
            "target/debug/patchbay-body-workbench-proof",
            "target/debug/browser-admission-probe",
        ],
    ),
    Step::typed(
        "prove.patchbay-body-workbench.identity-ledger",
        "Generate and validate the finite cross-manifestation Body identity ledger",
        "target/debug/patchbay-body-workbench-proof",
        &["target/conduit-evidence/patchbay-body-workbench/identity-ledger.json"],
        None,
        None,
        Some(ProofClass::HostedIntegration),
        &["target/conduit-evidence/patchbay-body-workbench/identity-ledger.json"],
    ),
    Step::typed(
        "prove.patchbay-body-workbench.html",
        "Prove HTML attachment, exact evidence retention, and semantic workbench composition",
        "cargo",
        &["test", "-p", "conduit-browser-patchbay-workbench"],
        None,
        None,
        Some(ProofClass::HostedIntegration),
        &[],
    ),
    Step::typed(
        "prove.patchbay-body-workbench.native",
        "Prove native Program, Body, History, Exact, Linear, and action composition deterministically",
        "cargo",
        &["test", "-p", "patchbay-native", "--all-targets"],
        None,
        None,
        Some(ProofClass::HostedIntegration),
        &[],
    ),
    Step::typed(
        "prove.patchbay-body-workbench.browser",
        "Prove hosted/external Body workbenches and exact Program-to-Body Follow in pinned Chromium",
        "node",
        &[
            "proof/browser/node_modules/@playwright/test/cli.js",
            "test",
            "--config",
            "proof/browser/patchbay-html.playwright.config.mjs",
            "proof/browser/patchbay-body-workbench.spec.mjs",
            "proof/browser/patchbay-follow.spec.mjs",
            "proof/browser/patchbay-authoring.spec.mjs",
        ],
        None,
        Some("playwright"),
        Some(ProofClass::LiveBrowser),
        &[],
    ),
];
