use crate::{process::Step, proof::ProofClass};

pub const PROVE_BODY_MEMBERSHIP_STEPS: &[Step] = &[
    Step::typed(
        "prove.body-membership.core",
        "Run bounded Body membership, admission, topology, and continuity conformance",
        "cargo",
        &["test", "-p", "conduit-body"],
        None,
        None,
        Some(ProofClass::DeterministicUnit),
        &[],
    ),
    Step::typed(
        "prove.body-membership.browser-runtime",
        "Prove browser-owned admission identity",
        "cargo",
        &["test", "-p", "conduit-browser-runtime", "membership"],
        None,
        None,
        Some(ProofClass::DeterministicUnit),
        &[],
    ),
    Step::typed(
        "prove.body-membership.browser-parts",
        "Prove three browser Parts and immutable replanning",
        "cargo",
        &[
            "test",
            "-p",
            "conduit-browser-sim",
            "--test",
            "body_membership",
            "--test",
            "part_replan",
            "--test",
            "body_hostile",
        ],
        None,
        None,
        Some(ProofClass::DeterministicSimulation),
        &[],
    ),
    Step::typed(
        "prove.body-membership.pico",
        "Prove provisioned Pico candidacy, admission, and planning",
        "cargo",
        &["test", "-p", "conduit-pico-sim", "--test", "body_admission"],
        None,
        None,
        Some(ProofClass::DeterministicSimulation),
        &[],
    ),
    Step::typed(
        "prove.body-membership.parts-view",
        "Prove human-first Parts projection from canonical truth",
        "cargo",
        &["test", "-p", "patchbay-model", "parts_view"],
        None,
        None,
        Some(ProofClass::DeterministicUnit),
        &[],
    ),
    Step::typed(
        "prove.body-membership.native-parts",
        "Prove native Parts drawing, exact inspection, and pointer-keyboard parity",
        "cargo",
        &["test", "-p", "patchbay-native", "parts"],
        None,
        None,
        Some(ProofClass::DeterministicUnit),
        &[],
    ),
    Step::typed(
        "prove.body-membership.native-ambient-admission",
        "Prove native Patchbay keeps an ambient browser inert until explicit Admit and exact proof",
        "cargo",
        &[
            "test",
            "-p",
            "patchbay-native",
            "ambient_page_stays_candidate_until_explicit_admit_completes_exact_proof",
        ],
        None,
        None,
        Some(ProofClass::LiveTransport),
        &[],
    ),
    Step::typed(
        "prove.body-membership.browser-wasm-build",
        "Build the browser Host and admission proof WASM artifact",
        "cargo",
        &[
            "build",
            "-p",
            "conduit-browser-runtime",
            "--target",
            "wasm32-unknown-unknown",
            "--release",
        ],
        None,
        Some("wasm32-unknown-unknown"),
        Some(ProofClass::ContractCompile),
        &["hosts/browser/conduit_browser_runtime.wasm"],
    ),
    Step::typed(
        "prove.body-membership.browser-servers",
        "Build bounded browser chat and Body admission Line servers",
        "cargo",
        &[
            "build",
            "-p",
            "conduit-std-host",
            "--bin",
            "webchat-server",
            "--bin",
            "browser-admission-probe",
            "--bin",
            "browser-spawn-probe",
        ],
        None,
        None,
        Some(ProofClass::ContractCompile),
        &[
            "target/debug/webchat-server",
            "target/debug/browser-admission-probe",
            "target/debug/browser-spawn-probe",
        ],
    ),
    Step::typed(
        "prove.body-membership.live-browser-admission",
        "Prove exact browser advertisement challenge proof and membership in Chromium",
        "npx",
        &[
            "playwright",
            "test",
            "--config",
            "hosts/browser/playwright.config.mjs",
            "hosts/browser/webchat.spec.mjs",
        ],
        None,
        Some("playwright"),
        Some(ProofClass::LiveBrowser),
        &[],
    ),
];

pub const PROVE_STD_BROWSER_S4_STEPS: &[Step] = &[
    Step::typed(
        "prove.std-browser-s4.wasm-build",
        "Build conduit-browser-runtime WASM artifact",
        "cargo",
        &[
            "build",
            "-p",
            "conduit-browser-runtime",
            "--target",
            "wasm32-unknown-unknown",
            "--release",
        ],
        None,
        Some("wasm32-unknown-unknown"),
        Some(ProofClass::ContractCompile),
        &["hosts/browser/conduit_browser_runtime.wasm"],
    ),
    Step::typed(
        "prove.std-browser-s4.patchbay-native-build",
        "Build native Patchbay distributed source artifact",
        "cargo",
        &["build", "-p", "patchbay-native"],
        None,
        None,
        Some(ProofClass::ContractCompile),
        &["target/debug/patchbay-native"],
    ),
    Step::typed(
        "prove.std-browser-s4.playwright",
        "Run Playwright distributed signal spec",
        "npx",
        &[
            "playwright",
            "test",
            "--config",
            "hosts/browser/playwright.config.mjs",
            "hosts/browser/distributed-signal.spec.mjs",
        ],
        None,
        Some("playwright"),
        Some(ProofClass::LiveBrowser),
        &[],
    ),
];

pub const PROVE_STD_BROWSER_TOGGLE_STEPS: &[Step] = &[
    Step::typed(
        "prove.std-browser-toggle.wasm-build",
        "Build conduit-browser-runtime WASM artifact",
        "cargo",
        &[
            "build",
            "-p",
            "conduit-browser-runtime",
            "--target",
            "wasm32-unknown-unknown",
            "--release",
        ],
        None,
        Some("wasm32-unknown-unknown"),
        Some(ProofClass::ContractCompile),
        &["hosts/browser/conduit_browser_runtime.wasm"],
    ),
    Step::typed(
        "prove.std-browser-toggle.playwright",
        "Run Playwright distributed toggle spec",
        "npx",
        &[
            "playwright",
            "test",
            "--config",
            "hosts/browser/playwright.config.mjs",
            "hosts/browser/distributed-toggle.spec.mjs",
        ],
        None,
        Some("playwright"),
        Some(ProofClass::LiveBrowser),
        &[],
    ),
];

pub const PROVE_BROWSER_HOST_STEPS: &[Step] = &[
    Step::typed(
        "prove.browser-host.wasm-build",
        "Build conduit-browser-runtime WASM artifact",
        "cargo",
        &[
            "build",
            "-p",
            "conduit-browser-runtime",
            "--target",
            "wasm32-unknown-unknown",
            "--release",
        ],
        None,
        Some("wasm32-unknown-unknown"),
        Some(ProofClass::ContractCompile),
        &["hosts/browser/conduit_browser_runtime.wasm"],
    ),
    Step::typed(
        "prove.browser-host.patchbay-native-build",
        "Build native Patchbay distributed source artifact",
        "cargo",
        &["build", "-p", "patchbay-native"],
        None,
        None,
        Some(ProofClass::ContractCompile),
        &["target/debug/patchbay-native"],
    ),
    Step::typed(
        "prove.browser-host.patchbay-html-build",
        "Build bounded HTML Patchbay delivery artifact",
        "cargo",
        &["build", "-p", "patchbay-html"],
        None,
        None,
        Some(ProofClass::ContractCompile),
        &["target/debug/patchbay-html"],
    ),
    Step::typed(
        "prove.browser-host.webchat-server-build",
        "Build bounded WebSocket chat server artifact",
        "cargo",
        &["build", "-p", "conduit-std-host", "--bin", "webchat-server"],
        None,
        None,
        Some(ProofClass::ContractCompile),
        &["target/debug/webchat-server"],
    ),
    Step::typed(
        "prove.browser-host.admission-server-build",
        "Build bounded browser Body admission proof server artifact",
        "cargo",
        &[
            "build",
            "-p",
            "conduit-std-host",
            "--bin",
            "browser-admission-probe",
            "--bin",
            "browser-spawn-probe",
        ],
        None,
        None,
        Some(ProofClass::ContractCompile),
        &[
            "target/debug/browser-admission-probe",
            "target/debug/browser-spawn-probe",
        ],
    ),
    Step::typed(
        "prove.browser-host.pool-webchat-server-build",
        "Build bounded shared-pool chat server artifact",
        "cargo",
        &[
            "build",
            "-p",
            "conduit-std-host",
            "--bin",
            "pool-webchat-server",
        ],
        None,
        None,
        Some(ProofClass::ContractCompile),
        &["target/debug/pool-webchat-server"],
    ),
    Step::typed(
        "prove.browser-host.r1-three-peer-input-server-build",
        "Build bounded R1 three-peer input server artifact",
        "cargo",
        &[
            "build",
            "-p",
            "conduit-std-host",
            "--bin",
            "r1-three-peer-input-server",
        ],
        None,
        None,
        Some(ProofClass::ContractCompile),
        &["target/debug/r1-three-peer-input-server"],
    ),
    Step::typed(
        "prove.browser-host.playwright",
        "Run browser host test suite",
        "npm",
        &["run", "test:browser-host"],
        None,
        Some("playwright"),
        Some(ProofClass::LiveBrowser),
        &[],
    ),
    Step::typed(
        "prove.browser-host.patchbay-html-matrix",
        "Run read-only HTML Patchbay browser matrix",
        "npx",
        &[
            "playwright",
            "test",
            "--config",
            "hosts/browser/patchbay-html.playwright.config.mjs",
        ],
        None,
        Some("playwright"),
        Some(ProofClass::LiveBrowser),
        &[],
    ),
];
