use crate::{process::Step, proof::ProofClass};

pub const PROVE_BODY_MEMBERSHIP_STEPS: &[Step] = &[
    Step::typed(
        "prove.body-membership.core",
        "Run bounded Body membership, admission, topology, and continuity conformance",
        "cargo",
        &["test", "-p", "conduit-body"],
        None,
        None,
        Some(ProofClass::DeterministicUnit),
        &[],
    ),
    Step::typed(
        "prove.body-membership.browser-runtime",
        "Prove browser-owned admission identity",
        "cargo",
        &["test", "-p", "conduit-browser-runtime", "membership"],
        None,
        None,
        Some(ProofClass::DeterministicUnit),
        &[],
    ),
    Step::typed(
        "prove.body-membership.browser-parts",
        "Prove three browser Parts and immutable replanning",
        "cargo",
        &[
            "test",
            "-p",
            "conduit-browser-sim",
            "--test",
            "body_membership",
            "--test",
            "part_replan",
            "--test",
            "body_hostile",
        ],
        None,
        None,
        Some(ProofClass::DeterministicSimulation),
        &[],
    ),
    Step::typed(
        "prove.body-membership.pico",
        "Prove provisioned Pico candidacy, admission, and planning",
        "cargo",
        &["test", "-p", "conduit-pico-sim", "--test", "body_admission"],
        None,
        None,
        Some(ProofClass::DeterministicSimulation),
        &[],
    ),
    Step::typed(
        "prove.body-membership.pico-usb-admission",
        "Prove the bounded Pico USB admission codec enters canonical Body truth",
        "cargo",
        &["test", "-p", "conduit-std-host", "--lib", "pico_admission"],
        None,
        None,
        Some(ProofClass::DeterministicUnit),
        &[],
    ),
    Step::typed(
        "prove.body-membership.pico-firmware-admission",
        "Compile the provisioned Pico admission responder for Thumb",
        "cargo",
        &[
            "check",
            "--locked",
            "--manifest-path",
            "firmware/conduit-pico-w-signal/Cargo.toml",
            "--target",
            "thumbv6m-none-eabi",
            "--release",
        ],
        None,
        Some("thumbv6m-none-eabi"),
        Some(ProofClass::ContractCompile),
        &[],
    ),
    Step::typed(
        "prove.body-membership.parts-view",
        "Prove human-first Parts projection from canonical truth",
        "cargo",
        &["test", "-p", "patchbay-model", "parts_view"],
        None,
        None,
        Some(ProofClass::DeterministicUnit),
        &[],
    ),
    Step::typed(
        "prove.body-membership.native-parts",
        "Prove native Parts drawing, exact inspection, and pointer-keyboard parity",
        "cargo",
        &["test", "-p", "patchbay-native", "parts"],
        None,
        None,
        Some(ProofClass::DeterministicUnit),
        &[],
    ),
    Step::typed(
        "prove.body-membership.native-ambient-admission",
        "Prove native Patchbay admits and renews exact presence until session loss projects offline",
        "cargo",
        &[
            "test",
            "-p",
            "patchbay-native",
            "ambient_page_admits_then_live_owner_projects_session_loss_offline",
        ],
        None,
        None,
        Some(ProofClass::LiveTransport),
        &[],
    ),
    Step::typed(
        "prove.body-membership.browser-wasm-build",
        "Build the browser Host and admission proof WASM artifact",
        "cargo",
        &[
            "build",
            "-p",
            "conduit-browser-runtime",
            "--target",
            "wasm32-unknown-unknown",
            "--release",
        ],
        None,
        Some("wasm32-unknown-unknown"),
        Some(ProofClass::ContractCompile),
        &["hosts/browser/conduit_browser_runtime.wasm"],
    ),
    Step::typed(
        "prove.body-membership.browser-servers",
        "Build bounded browser chat and Body admission Line servers",
        "cargo",
        &[
            "build",
            "-p",
            "conduit-std-host",
            "--bin",
            "webchat-server",
            "--bin",
            "browser-admission-probe",
            "--bin",
            "browser-spawn-probe",
        ],
        None,
        None,
        Some(ProofClass::ContractCompile),
        &[
            "target/debug/webchat-server",
            "target/debug/browser-admission-probe",
            "target/debug/browser-spawn-probe",
        ],
    ),
    Step::typed(
        "prove.body-membership.browser-parts-capstone-build",
        "Build the bounded native Body browser Parts and front-door capstones",
        "cargo",
        &[
            "build",
            "-p",
            "patchbay-native",
            "--bin",
            "browser-parts-capstone",
            "--bin",
            "patchbay-front-door-capstone",
        ],
        None,
        None,
        Some(ProofClass::ContractCompile),
        &[
            "target/debug/browser-parts-capstone",
            "target/debug/patchbay-front-door-capstone",
        ],
    ),
    Step::typed(
        "prove.body-membership.live-browser-admission",
        "Prove exact browser advertisement challenge proof and membership in Chromium",
        "npx",
        &[
            "playwright",
            "test",
            "--config",
            "hosts/browser/playwright.config.mjs",
            "hosts/browser/webchat.spec.mjs",
        ],
        None,
        Some("playwright"),
        Some(ProofClass::LiveBrowser),
        &[],
    ),
];

pub const PROVE_BODY_MEMBERSHIP_HIL_BROWSER_STEPS: &[Step] = &[
    Step::typed(
        "prove.body-membership-hil.browser-runtime",
        "Build the browser Host WASM artifact for the physical Body capstone",
        "cargo",
        &[
            "build",
            "-p",
            "conduit-browser-runtime",
            "--target",
            "wasm32-unknown-unknown",
            "--release",
        ],
        None,
        Some("wasm32-unknown-unknown"),
        Some(ProofClass::ContractCompile),
        &["hosts/browser/conduit_browser_runtime.wasm"],
    ),
    Step::typed(
        "prove.body-membership-hil.native",
        "Build the native same-Body physical membership verifier",
        "cargo",
        &[
            "build",
            "-p",
            "patchbay-native",
            "--bin",
            "browser-parts-capstone",
        ],
        None,
        None,
        Some(ProofClass::ContractCompile),
        &["target/debug/browser-parts-capstone"],
    ),
    Step::typed(
        "prove.body-membership-hil.browser-servers",
        "Build the bounded browser Lines used by the physical Body capstone",
        "cargo",
        &["build", "-p", "conduit-std-host", "--bin", "webchat-server"],
        None,
        None,
        Some(ProofClass::ContractCompile),
        &["target/debug/webchat-server"],
    ),
    Step::typed(
        "prove.body-membership-hil.live-browser-membership",
        "Admit three Chromium Parts and the physical Pico into the exact R1 Body",
        "npx",
        &[
            "playwright",
            "test",
            "--config",
            "hosts/browser/playwright.config.mjs",
            "hosts/browser/webchat.spec.mjs",
            "--grep",
            "one native Body presents three mixed browser Parts",
        ],
        None,
        Some("playwright"),
        Some(ProofClass::PhysicalCrossHost),
        &[],
    ),
];

pub const PROVE_STD_BROWSER_S4_STEPS: &[Step] = &[
    Step::typed(
        "prove.std-browser-s4.wasm-build",
        "Build conduit-browser-runtime WASM artifact",
        "cargo",
        &[
            "build",
            "-p",
            "conduit-browser-runtime",
            "--target",
            "wasm32-unknown-unknown",
            "--release",
        ],
        None,
        Some("wasm32-unknown-unknown"),
        Some(ProofClass::ContractCompile),
        &["hosts/browser/conduit_browser_runtime.wasm"],
    ),
    Step::typed(
        "prove.std-browser-s4.patchbay-native-build",
        "Build native Patchbay distributed source artifact",
        "cargo",
        &["build", "-p", "patchbay-native"],
        None,
        None,
        Some(ProofClass::ContractCompile),
        &["target/debug/patchbay-native"],
    ),
    Step::typed(
        "prove.std-browser-s4.playwright",
        "Run Playwright distributed signal spec",
        "npx",
        &[
            "playwright",
            "test",
            "--config",
            "hosts/browser/playwright.config.mjs",
            "hosts/browser/distributed-signal.spec.mjs",
        ],
        None,
        Some("playwright"),
        Some(ProofClass::LiveBrowser),
        &[],
    ),
];

pub const PROVE_STD_BROWSER_TOGGLE_STEPS: &[Step] = &[
    Step::typed(
        "prove.std-browser-toggle.wasm-build",
        "Build conduit-browser-runtime WASM artifact",
        "cargo",
        &[
            "build",
            "-p",
            "conduit-browser-runtime",
            "--target",
            "wasm32-unknown-unknown",
            "--release",
        ],
        None,
        Some("wasm32-unknown-unknown"),
        Some(ProofClass::ContractCompile),
        &["hosts/browser/conduit_browser_runtime.wasm"],
    ),
    Step::typed(
        "prove.std-browser-toggle.playwright",
        "Run Playwright distributed toggle spec",
        "npx",
        &[
            "playwright",
            "test",
            "--config",
            "hosts/browser/playwright.config.mjs",
            "hosts/browser/distributed-toggle.spec.mjs",
        ],
        None,
        Some("playwright"),
        Some(ProofClass::LiveBrowser),
        &[],
    ),
];

pub const PROVE_BROWSER_HOST_STEPS: &[Step] = &[
    Step::typed(
        "prove.browser-host.wasm-build",
        "Build conduit-browser-runtime WASM artifact",
        "cargo",
        &[
            "build",
            "-p",
            "conduit-browser-runtime",
            "--target",
            "wasm32-unknown-unknown",
            "--release",
        ],
        None,
        Some("wasm32-unknown-unknown"),
        Some(ProofClass::ContractCompile),
        &["hosts/browser/conduit_browser_runtime.wasm"],
    ),
    Step::typed(
        "prove.browser-host.patchbay-native-build",
        "Build native Patchbay distributed source artifact",
        "cargo",
        &["build", "-p", "patchbay-native"],
        None,
        None,
        Some(ProofClass::ContractCompile),
        &[
            "target/debug/patchbay-native",
            "target/debug/browser-parts-capstone",
        ],
    ),
    Step::typed(
        "prove.browser-host.patchbay-html-build",
        "Build bounded HTML Patchbay delivery artifact",
        "cargo",
        &["build", "-p", "patchbay-html"],
        None,
        None,
        Some(ProofClass::ContractCompile),
        &["target/debug/patchbay-html"],
    ),
    Step::typed(
        "prove.browser-host.webchat-server-build",
        "Build bounded WebSocket chat server artifact",
        "cargo",
        &["build", "-p", "conduit-std-host", "--bin", "webchat-server"],
        None,
        None,
        Some(ProofClass::ContractCompile),
        &["target/debug/webchat-server"],
    ),
    Step::typed(
        "prove.browser-host.admission-server-build",
        "Build bounded browser Body admission proof server artifact",
        "cargo",
        &[
            "build",
            "-p",
            "conduit-std-host",
            "--bin",
            "browser-admission-probe",
            "--bin",
            "browser-spawn-probe",
        ],
        None,
        None,
        Some(ProofClass::ContractCompile),
        &[
            "target/debug/browser-admission-probe",
            "target/debug/browser-spawn-probe",
        ],
    ),
    Step::typed(
        "prove.browser-host.pool-webchat-server-build",
        "Build bounded shared-pool chat server artifact",
        "cargo",
        &[
            "build",
            "-p",
            "conduit-std-host",
            "--bin",
            "pool-webchat-server",
        ],
        None,
        None,
        Some(ProofClass::ContractCompile),
        &["target/debug/pool-webchat-server"],
    ),
    Step::typed(
        "prove.browser-host.r1-three-peer-input-server-build",
        "Build bounded R1 three-peer input server artifact",
        "cargo",
        &[
            "build",
            "-p",
            "conduit-std-host",
            "--bin",
            "r1-three-peer-input-server",
        ],
        None,
        None,
        Some(ProofClass::ContractCompile),
        &["target/debug/r1-three-peer-input-server"],
    ),
    Step::typed(
        "prove.browser-host.playwright",
        "Run browser host test suite",
        "npm",
        &["run", "test:browser-host"],
        None,
        Some("playwright"),
        Some(ProofClass::LiveBrowser),
        &[],
    ),
    Step::typed(
        "prove.browser-host.patchbay-html-matrix",
        "Run read-only HTML Patchbay browser matrix",
        "npx",
        &[
            "playwright",
            "test",
            "--config",
            "hosts/browser/patchbay-html.playwright.config.mjs",
        ],
        None,
        Some("playwright"),
        Some(ProofClass::LiveBrowser),
        &[],
    ),
];

pub const PROVE_PATCHBAY_FRONT_DOOR_STEPS: &[Step] = &[
    Step::typed(
        "prove.patchbay-front-door.semantic",
        "Prove zero-Body entry, inert OPEN, explicit JOIN/BIRTH, refusal Signs, and post-transition Plan/Play truth",
        "cargo",
        &["test", "-p", "patchbay-model", "front_door"],
        None,
        None,
        Some(ProofClass::DeterministicUnit),
        &[],
    ),
    Step::typed(
        "prove.patchbay-front-door.equivalence",
        "Prove native and browser zero-Body semantic equivalence with deliberate drift refusal",
        "cargo",
        &["test", "-p", "patchbay-model", "renderer_execution_tests"],
        None,
        None,
        Some(ProofClass::DeterministicUnit),
        &[],
    ),
    Step::typed(
        "prove.patchbay-front-door.native",
        "Prove the native manifestation enters the shared revisioned WORLD without a synthetic Body",
        "cargo",
        &["test", "-p", "patchbay-native", "native_front_door"],
        None,
        None,
        Some(ProofClass::HostedIntegration),
        &[],
    ),
    Step::typed(
        "prove.patchbay-front-door.browser-wasm",
        "Build the browser Host admission identity and kernel artifact",
        "cargo",
        &[
            "build",
            "-p",
            "conduit-browser-runtime",
            "--target",
            "wasm32-unknown-unknown",
            "--release",
        ],
        None,
        Some("wasm32-unknown-unknown"),
        Some(ProofClass::ContractCompile),
        &["hosts/browser/conduit_browser_runtime.wasm"],
    ),
    Step::typed(
        "prove.patchbay-front-door.artifacts",
        "Build the native, HTML, and live front-door capstone artifacts",
        "cargo",
        &[
            "build",
            "-p",
            "patchbay-native",
            "--bin",
            "patchbay-native",
            "--bin",
            "patchbay-front-door-capstone",
            "-p",
            "patchbay-html",
        ],
        None,
        None,
        Some(ProofClass::ContractCompile),
        &[
            "target/debug/patchbay-native",
            "target/debug/patchbay-front-door-capstone",
            "target/debug/patchbay-html",
        ],
    ),
    Step::typed(
        "prove.patchbay-front-door.membership-line",
        "Build the bounded Line used by real browser Part admission",
        "cargo",
        &["build", "-p", "conduit-std-host", "--bin", "webchat-server"],
        None,
        None,
        Some(ProofClass::ContractCompile),
        &["target/debug/webchat-server"],
    ),
    Step::typed(
        "prove.patchbay-front-door.browser",
        "Run zero-Body OPEN, stale refusal, explicit BIRTH, Plan, and Play through one pinned Chromium manifestation",
        "npx",
        &[
            "playwright",
            "test",
            "--config",
            "hosts/browser/patchbay-html.playwright.config.mjs",
            "hosts/browser/patchbay-front-door.spec.mjs",
        ],
        None,
        Some("playwright"),
        Some(ProofClass::LiveBrowser),
        &[],
    ),
    Step::typed(
        "prove.patchbay-front-door.live-membership",
        "Admit a real Chromium Part into the presented Body, observe it offline, preserve the Plan, and replan",
        "npx",
        &[
            "playwright",
            "test",
            "--config",
            "hosts/browser/playwright.config.mjs",
            "hosts/browser/webchat.spec.mjs",
            "--grep",
            "Patchbay front door presents one live browser Part",
        ],
        None,
        Some("playwright"),
        Some(ProofClass::LiveBrowser),
        &[],
    ),
];
