//! Exact typed contracts and offers installed by the executable std nucleus.

use super::*;

/// Exact typed contracts currently supported by the executable `conduit.std` nucleus.
///
/// This deliberately excludes the eight legacy contracts returned by
/// [`standard_contracts`]. Those revisions use `value/any` and remain audited
/// compatibility fixtures rather than supported operations.
pub fn supported_nucleus_contracts() -> Vec<StandardKindContract> {
    vec![
        tick_contract(),
        time_every_contract(),
        audio_render_demand_contract(),
        music_synth_contract(),
        time_debounce_contract(),
        time_timeout_contract(),
        time_delay_contract(),
        time_throttle_contract(),
        tick_presentation_contract(),
        bool_presentation_contract(),
        text_literal_contract(),
        text_upper_contract(),
        text_join_contract(),
        text_presentation_contract(),
        key_event_tee_contract(),
        keymap_contract(),
        chords_contract(),
        state_count_contract(),
        state_toggle_contract(),
        count_presentation_contract(),
        state_latest_scalar_contract(),
        flow_tee_scalar_contract(),
        flow_gate_scalar_contract(),
        logic_compare_scalar_contract(),
        logic_not_contract(),
        logic_select_scalar_contract(),
        math_clamp_contract(),
        math_scale_contract(),
        math_deadband_contract(),
        layout_viewport_contract(),
        layout_inset_contract(),
        layout_row_contract(),
        layout_column_contract(),
        layout_stack_contract(),
        layout_align_contract(),
        presentation_icon_contract(),
        presentation_frame_contract(),
        presentation_badge_contract(),
        graphics_rect_contract(),
        graphics_text_contract(),
        graphics_icon_contract(),
        graphics_presentation_contract(),
        patchbay_presentation_contracts()[0].clone(),
        patchbay_presentation_contracts()[1].clone(),
        patchbay_presentation_contracts()[2].clone(),
        patchbay_presentation_contracts()[3].clone(),
        robotics_observe_bump_contract(),
        robotics_observe_imu_contract(),
        robotics_observe_range_contract(),
        robotics_observe_odometry_contract(),
        robotics_observe_battery_contract(),
        robotics_velocity_intent_contract(),
        robotics_drive_differential_contract(),
        copy_file_contract(),
        json_encode_contract(),
        json_decode_contract(),
    ]
}

/// One exact accepted implementation offer corresponding to each supported contract.
///
/// These values include the revision, implementation, artifact, resource,
/// host-operation, and finite-limit facts that an immutable Plan seals after
/// checked-face compatibility and admission filtering.
pub fn supported_nucleus_offers() -> Vec<conduit_core::CapabilityOffer> {
    vec![
        tick_capability_offer(),
        time_every_offer(),
        audio_render_demand_offer(),
        music_synth_reference_offer(),
        time_debounce_offer(),
        time_timeout_offer(),
        time_delay_offer(),
        time_throttle_offer(),
        tick_presentation_offer(),
        bool_presentation_std_offer(),
        text_literal_offer(),
        text_upper_offer(),
        text_join_offer(),
        text_presentation_offer(),
        key_event_tee_offer(),
        keymap_offer(),
        chords_offer(),
        state_count_offer(),
        state_toggle_offer(),
        count_presentation_offer(),
        state_latest_scalar_offer(),
        flow_tee_scalar_offer(),
        flow_gate_scalar_offer(),
        logic_compare_scalar_offer(),
        logic_not_offer(),
        logic_select_scalar_offer(),
        math_clamp_offer(),
        math_scale_offer(),
        math_deadband_offer(),
        layout_viewport_offer(),
        layout_inset_offer(),
        layout_row_offer(),
        layout_column_offer(),
        layout_stack_offer(),
        layout_align_offer(),
        presentation_icon_offer(),
        presentation_frame_offer(),
        presentation_badge_offer(),
        graphics_rect_offer(),
        graphics_text_offer(),
        graphics_icon_offer(),
        graphics_presentation_offer(),
        patchbay_presentation_offers()[0].clone(),
        patchbay_presentation_offers()[1].clone(),
        patchbay_presentation_offers()[2].clone(),
        patchbay_presentation_offers()[3].clone(),
        robotics_observe_bump_offer(),
        robotics_observe_imu_offer(),
        robotics_observe_range_offer(),
        robotics_observe_odometry_offer(),
        robotics_observe_battery_offer(),
        robotics_velocity_intent_offer(),
        robotics_drive_differential_offer(),
        copy_file_offer(),
        json_encode_std_offer(),
        json_decode_std_offer(),
    ]
}
