[package]
name = "conduit-workspace-fabrication"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
conduit-host-fabrication = { path = "../conduit-host-fabrication" }
conduit-host-browser-fabrication = { path = "../../hosts/browser-host/fabrication-package" }
conduit-host-conduitos-fabrication = { path = "../../hosts/conduitos/fabrication-package" }
conduit-host-esp32-fabrication = { path = "../../firmware/conduit-esp32-wroom-signal/fabrication-package" }
conduit-host-hosted = { path = "../../hosts/std/fabrication-package" }
conduit-linear-framebuffer-fabrication = { path = "../../hosts/fabrication/linear-framebuffer" }
conduit-host-rp2040 = { path = "../../firmware/conduit-pico-w-signal/fabrication-package" }
conduit-host-raspberry-pi = { path = "../../hosts/raspberry-pi/fabrication-package" }
