pub mod adversarial_profile;
pub mod check_all;
pub mod check_python_boundary;
pub mod embedded_gate;
pub mod generate_browser_plan;
pub mod performance_gate;
pub mod rp2040_hil;
pub mod serve;
pub mod verify_canonical;
