//! Deterministic subsetting and native rasterization for canonical palette icons.

use std::fmt::Write as _;
use std::fs;
use std::path::Path;

use conduit_semantic_catalog::PaletteIconKey;
use resvg::{tiny_skia, usvg};

use crate::cli::PaletteIconsArgs;

const SIDE: u32 = 16;

pub fn run(args: PaletteIconsArgs) -> Result<(), Box<dyn std::error::Error>> {
    let mut generated = String::from(
        "//! @generated by `cargo xtask palette-icons`; do not edit.\n\nuse patchbay_model::PaletteIconKey;\n\n",
    );
    let mut expected_names = Vec::new();
    for key in PaletteIconKey::ALL_UPSTREAM {
        let name = key.as_str();
        expected_names.push(format!("{name}.svg"));
        let source = fs::read_to_string(args.input.join(format!("{name}.svg")))?;
        let mask = rasterize(&source)?;
        writeln!(generated, "const {}: [u16; 16] = [", constant_name(key))?;
        for row in mask {
            writeln!(generated, "    0b{row:016b},")?;
        }
        generated.push_str("];\n\n");
    }
    validate_exact_subset(&args.input, &expected_names)?;
    generated.push_str(
        "pub const fn mask(key: PaletteIconKey) -> Option<&'static [u16; 16]> {\n    match key {\n",
    );
    for key in PaletteIconKey::ALL_UPSTREAM {
        writeln!(
            generated,
            "        PaletteIconKey::{key:?} => Some(&{}),",
            constant_name(key)
        )?;
    }
    generated.push_str("        PaletteIconKey::GenericGear => None,\n    }\n}\n");
    fs::write(args.output, generated)?;
    Ok(())
}

fn rasterize(svg: &str) -> Result<[u16; SIDE as usize], Box<dyn std::error::Error>> {
    let options = usvg::Options::default();
    let tree = usvg::Tree::from_str(svg, &options)?;
    let mut pixmap = tiny_skia::Pixmap::new(SIDE, SIDE).ok_or("could not allocate icon pixmap")?;
    let scale = SIDE as f32 / 24.0;
    resvg::render(
        &tree,
        tiny_skia::Transform::from_scale(scale, scale),
        &mut pixmap.as_mut(),
    );
    let mut rows = [0_u16; SIDE as usize];
    for y in 0..SIDE {
        for x in 0..SIDE {
            let alpha = pixmap.pixel(x, y).map_or(0, |pixel| pixel.alpha());
            if alpha >= 32 {
                rows[y as usize] |= 1 << (SIDE - 1 - x);
            }
        }
    }
    Ok(rows)
}

fn validate_exact_subset(
    input: &Path,
    expected: &[String],
) -> Result<(), Box<dyn std::error::Error>> {
    let mut actual = fs::read_dir(input)?
        .filter_map(Result::ok)
        .filter(|entry| entry.path().extension().and_then(|value| value.to_str()) == Some("svg"))
        .map(|entry| entry.file_name().to_string_lossy().into_owned())
        .collect::<Vec<_>>();
    actual.sort();
    let mut expected = expected.to_vec();
    expected.sort();
    if actual != expected {
        return Err(
            format!("Lucide subset differs: expected {expected:?}, found {actual:?}").into(),
        );
    }
    Ok(())
}

const fn constant_name(key: PaletteIconKey) -> &'static str {
    match key {
        PaletteIconKey::Clock => "CLOCK",
        PaletteIconKey::Repeat2 => "REPEAT_2",
        PaletteIconKey::Presentation => "PRESENTATION",
        PaletteIconKey::Type => "TYPE",
        PaletteIconKey::CaseUpper => "CASE_UPPER",
        PaletteIconKey::Combine => "COMBINE",
        PaletteIconKey::Tally5 => "TALLY_5",
        PaletteIconKey::ChartColumnsIncreasing => "CHART_COLUMNS_INCREASING",
        PaletteIconKey::FileOutput => "FILE_OUTPUT",
        PaletteIconKey::Keyboard => "KEYBOARD",
        PaletteIconKey::GenericGear => "GENERIC_GEAR",
    }
}
