[package]
name = "conduit-web"
version = "0.1.0"
edition = "2021"

[dependencies]
conduit-core = { path = "../conduit-core" }
conduit-form = { path = "../conduit-form", optional = true }
serde = { version = "1", default-features = false, features = ["alloc", "derive"] }

[features]
default = ["form-catalog"]
form-catalog = ["dep:conduit-form"]
