import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdtemp, mkdir, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { assertSourceCheckout } from '../../tools/ci/pipeline/source.mjs';

async function fixture(t) {
  const directory = await mkdtemp(path.join(os.tmpdir(), 'pipeline-source-'));
  t.after(() => rm(directory, { recursive: true, force: true }));
  const git = (...args) => execFileSync('git', args, { cwd: directory, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }).trim();
  git('init');
  git('config', 'user.name', 'Pipeline proof');
  git('config', 'user.email', 'pipeline@example.invalid');
  git('config', 'commit.gpgsign', 'false');
  await writeFile(path.join(directory, '.gitignore'), '/target/\n/node_modules/\n');
  await writeFile(path.join(directory, 'source.mjs'), 'export const value = 1;\n');
  git('add', '.');
  git('commit', '-m', 'Fixture source');
  const sha = git('rev-parse', 'HEAD');
  return { directory, git, check: () => assertSourceCheckout(sha, directory) };
}

test('accepts exact clean source with ignored generated artifacts before and after proof', async t => {
  const f = await fixture(t);
  f.check();
  for (const name of ['target', 'node_modules']) {
    await mkdir(path.join(f.directory, name));
    await writeFile(path.join(f.directory, name, 'generated'), 'generated bytes');
  }
  f.check();
});

for (const staged of [false, true]) {
  test(`rejects ${staged ? 'staged' : 'unstaged'} tracked source changes`, async t => {
    const f = await fixture(t);
    f.check();
    await writeFile(path.join(f.directory, 'source.mjs'), 'export const value = 2;\n');
    if (staged) f.git('add', 'source.mjs');
    assert.throws(f.check, /Source checkout check failed/);
  });
}

test('rejects nonignored untracked source before proof and introduced during proof', async t => {
  const f = await fixture(t);
  const source = path.join(f.directory, 'extra.mjs');
  await writeFile(source, 'uncommitted staged asset');
  assert.throws(f.check, /untracked files: "extra.mjs"/);
  await rm(source);
  f.check();
  await writeFile(source, 'asset introduced during proof');
  assert.throws(f.check, /untracked files: "extra.mjs"/);
});

test('rejects a changed HEAD even when tracked source is clean', async t => {
  const f = await fixture(t);
  f.check();
  f.git('commit', '--allow-empty', '-m', 'Different source identity');
  assert.throws(f.check, /does not match source SHA/);
});
