[package]
name = "conduit-avr-promicro-host"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]
resolver = "2"

[dependencies]
arduino-hal = { git = "https://github.com/Rahix/avr-hal.git", rev = "0be252f2a899dbd687a26f8561048ce61854eaae", features = ["sparkfun-promicro"] }
atmega-hal = { git = "https://github.com/Rahix/avr-hal.git", rev = "0be252f2a899dbd687a26f8561048ce61854eaae", features = ["atmega32u4"] }
avr-device = { version = "0.7", features = ["atmega32u4"] }
conduit-assigned-plan = { path = "../../../../architecture/assigned-plan" }
conduit-create-oi = { path = "../../../../mechanisms/devices/create-oi" }
conduit-kernel = { path = "../../../../architecture/kernel" }
embedded-hal-v0 = { package = "embedded-hal", version = "0.2.7" }
nb = "1.1.0"
panic-halt = "1.0.0"
usb-device = "0.3.2"
usbd-serial = "0.2.2"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = "symbols"
