/// Exact reviewed binding from selectable browser device machinery to its
/// admitted chooser, acquired Base, and finite transfer realization.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BrowserDeviceRealizationDescriptor {
    pub fabrication_implementation_id: &'static str,
    pub implementation_revision: u32,
    pub acquisition_offer_id: &'static str,
    pub runtime_base_implementation_id: &'static str,
    pub adapter_artifact_id: &'static str,
    pub runtime_artifact_id: &'static str,
    pub chooser_operation: &'static str,
    pub request_authority: &'static str,
    pub use_authority: &'static str,
    pub maximum_active_devices: u16,
    pub maximum_transfers_in_flight: u16,
    pub maximum_transfer_bytes: u32,
    pub maximum_reads_or_in_transfers: u16,
    pub maximum_writes_or_out_transfers: u16,
    pub maximum_stream_milliseconds: u32,
    pub stable_hardware_identity: bool,
    pub requires_subsequent_use_plan: bool,
}

pub const BROWSER_DEVICE_REALIZATIONS: &[BrowserDeviceRealizationDescriptor] = &[
    BrowserDeviceRealizationDescriptor {
        fabrication_implementation_id: "browser/webserial@1",
        implementation_revision: 1,
        acquisition_offer_id: "device/acquire-webserial@1",
        runtime_base_implementation_id: "browser/web-serial@1",
        adapter_artifact_id: "browser-host/device-base.mjs@1",
        runtime_artifact_id: "conduit-browser-runtime/device-base@1",
        chooser_operation: "conduit.host/acquire-web-serial@1",
        request_authority: "conduit.authority/request-browser-device@1",
        use_authority: "conduit.authority/use-browser-device@1",
        maximum_active_devices: 1,
        maximum_transfers_in_flight: 1,
        maximum_transfer_bytes: 4096,
        maximum_reads_or_in_transfers: 8,
        maximum_writes_or_out_transfers: 8,
        maximum_stream_milliseconds: 60_000,
        stable_hardware_identity: false,
        requires_subsequent_use_plan: true,
    },
    BrowserDeviceRealizationDescriptor {
        fabrication_implementation_id: "browser/webusb@1",
        implementation_revision: 1,
        acquisition_offer_id: "device/acquire-webusb@1",
        runtime_base_implementation_id: "browser/web-usb@1",
        adapter_artifact_id: "browser-host/usb-device-base.mjs@1",
        runtime_artifact_id: "conduit-browser-runtime/web-usb-base@1",
        chooser_operation: "conduit.host/acquire-web-usb@1",
        request_authority: "conduit.authority/request-browser-device@1",
        use_authority: "conduit.authority/use-browser-device@1",
        maximum_active_devices: 1,
        maximum_transfers_in_flight: 1,
        maximum_transfer_bytes: 4096,
        maximum_reads_or_in_transfers: 8,
        maximum_writes_or_out_transfers: 8,
        maximum_stream_milliseconds: 0,
        stable_hardware_identity: false,
        requires_subsequent_use_plan: true,
    },
];
