use crate::process::Step;

pub(super) const STEPS: &[Step] = &[
    Step::new(
        "owner-presentation.direct-reading",
        "Prove acknowledged direct Show reading, remaining-item scope and cancellation",
        "cargo",
        &[
            "test",
            "--locked",
            "-p",
            "conduit",
            "--bin",
            "conduit",
            "direct_reading_tests",
            "--",
            "--test-threads=1",
        ],
    ),
    Step::new(
        "owner-presentation.attachment",
        "Prove actual owner terminal Show, typed action and stale replacement refusal",
        "cargo",
        &[
            "test",
            "--locked",
            "-p",
            "conduit",
            "--bin",
            "conduit",
            "terminal_attach",
            "--",
            "--test-threads=1",
        ],
    ),
    Step::new(
        "owner-presentation.wardrobe",
        "Prove owner-held sealed alternatives and fresh acknowledgement",
        "cargo",
        &[
            "test",
            "--locked",
            "-p",
            "conduit",
            "--test",
            "owner_presentation_wardrobe",
        ],
    ),
    Step::new(
        "owner-presentation.seals",
        "Prove ordinary Mask Plans and exact finite route ensembles",
        "cargo",
        &[
            "test",
            "--locked",
            "-p",
            "conduit-presentation",
            "--test",
            "mask_plot",
            "--test",
            "mask_wardrobe",
        ],
    ),
    Step::new(
        "owner-presentation.carrier",
        "Prove missing, stale and lost browser carrier evidence refuses",
        "cargo",
        &[
            "test",
            "--locked",
            "-p",
            "conduit",
            "--bin",
            "conduit",
            "participants::service",
            "--",
            "--test-threads=1",
        ],
    ),
    Step::new(
        "owner-presentation.kernel",
        "Prove terminal Mask bounds, acknowledgement, cancellation and typed return",
        "cargo",
        &[
            "test",
            "--locked",
            "-p",
            "conduit-std-host",
            "--lib",
            "terminal_mask_execution::tests",
            "--",
            "--test-threads=1",
        ],
    ),
];
