use crate::prelude::*;
use crate::CheckedNativeType;
use alloc::collections::{BTreeMap, BTreeSet};
use conduit_core::{PrimitiveInfoKind, StructuredInfoType, StructuredInfoTypeShape};
use core::fmt::Write;

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct RustBindingOptions {
    /// A Rust-only spelling prefix. It never participates in semantic identity.
    pub type_prefix: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RustBindingModule {
    pub source: String,
    pub semantic_type_bytes: BTreeMap<String, Vec<u8>>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RustBindingGenerationError {
    EmptyTypeSet,
    InvalidRustIdentifier(String),
    DuplicateRustIdentifier(String),
    InvalidSemanticType,
    UnsupportedLeaf(String),
}

pub fn generate_rust_bindings(
    types: &[CheckedNativeType],
    options: &RustBindingOptions,
) -> Result<RustBindingModule, RustBindingGenerationError> {
    if types.is_empty() {
        return Err(RustBindingGenerationError::EmptyTypeSet);
    }
    let mut names = BTreeMap::new();
    let mut seen = BTreeSet::new();
    let mut semantic_type_bytes = BTreeMap::new();
    for value_type in types {
        let prefix = if options.type_prefix.is_empty() {
            String::new()
        } else {
            rust_pascal_identifier(&options.type_prefix)?
        };
        let rust_name = format!("{}{}", prefix, rust_pascal_identifier(&value_type.name)?);
        if !seen.insert(rust_name.clone()) {
            return Err(RustBindingGenerationError::DuplicateRustIdentifier(
                rust_name,
            ));
        }
        names.insert(value_type.identity.as_str().to_string(), rust_name);
        semantic_type_bytes.insert(
            value_type.identity.as_str().to_string(),
            value_type
                .value_type
                .canonical_bytes()
                .map_err(|_| RustBindingGenerationError::InvalidSemanticType)?,
        );
    }

    let mut source = String::from(
        "// @generated by Conduit from checked semantic Types.\n\
         // Rust names and layout are bindings, never semantic identity.\n\
         use conduit_form::rust_binding::{BoundedBytes, BoundedSequence, NativeBindingRefusal, NativeRustBinding};\n\
         use conduit_core::{StructuredFieldValue, StructuredInfoType, StructuredInfoValue, StructuredInfoValueShape};\n\
         use alloc::{string::String, vec::Vec};\n\n",
    );
    for value_type in types {
        emit_type(&mut source, value_type, &names, &semantic_type_bytes)?;
    }
    Ok(RustBindingModule {
        source,
        semantic_type_bytes,
    })
}

fn emit_type(
    out: &mut String,
    value_type: &CheckedNativeType,
    names: &BTreeMap<String, String>,
    bytes_by_identity: &BTreeMap<String, Vec<u8>>,
) -> Result<(), RustBindingGenerationError> {
    let rust_name = &names[value_type.identity.as_str()];
    let constant = format!("{}_SEMANTIC_TYPE", rust_screaming_identifier(rust_name)?);
    let bytes = &bytes_by_identity[value_type.identity.as_str()];
    writeln!(
        out,
        "pub const {constant}: &[u8] = &[{}];",
        byte_literals(bytes)
    )
    .expect("String writing is infallible");
    writeln!(
        out,
        "pub const {constant}_IDENTITY: &str = {:?};",
        value_type.identity.as_str()
    )
    .expect("String writing is infallible");

    match value_type.value_type.shape() {
        StructuredInfoTypeShape::Nominal { representation, .. } => {
            let inner = rust_type(representation, names)?;
            writeln!(
                out,
                "#[derive(Debug, Clone, PartialEq, Eq)]\npub struct {rust_name}({inner});"
            )
            .expect("String writing is infallible");
            writeln!(out, "impl {rust_name} {{").expect("String writing is infallible");
            writeln!(out, "    pub fn get(&self) -> &{inner} {{ &self.0 }}")
                .expect("String writing is infallible");
            writeln!(out, "}}\n").expect("String writing is infallible");
        }
        StructuredInfoTypeShape::Record { fields, .. } => {
            writeln!(
                out,
                "#[derive(Debug, Clone, PartialEq, Eq)]\npub struct {rust_name} {{"
            )
            .expect("String writing is infallible");
            for field in fields {
                writeln!(
                    out,
                    "    {}: {},",
                    rust_snake_identifier(field.name())?,
                    rust_type(field.value_type(), names)?
                )
                .expect("String writing is infallible");
            }
            writeln!(out, "}}\n").expect("String writing is infallible");
        }
        StructuredInfoTypeShape::Variant { cases, .. } => {
            for case in cases {
                if unit_type(case.payload_type()) {
                    continue;
                }
                let payload = format!("{rust_name}{}", rust_pascal_identifier(case.tag())?);
                emit_payload_struct(out, &payload, case.payload_type(), names)?;
            }
            writeln!(
                out,
                "#[derive(Debug, Clone, PartialEq, Eq)]\npub enum {rust_name} {{"
            )
            .expect("String writing is infallible");
            for case in cases {
                let variant = rust_pascal_identifier(case.tag())?;
                if unit_type(case.payload_type()) {
                    writeln!(out, "    {variant},").expect("String writing is infallible");
                } else {
                    writeln!(out, "    {variant}({rust_name}{variant}),")
                        .expect("String writing is infallible");
                }
            }
            writeln!(out, "}}\n").expect("String writing is infallible");
        }
        _ => return Err(RustBindingGenerationError::InvalidSemanticType),
    }
    emit_semantic_type_impl(out, rust_name, &constant);
    Ok(())
}

fn emit_payload_struct(
    out: &mut String,
    name: &str,
    value_type: &StructuredInfoType,
    names: &BTreeMap<String, String>,
) -> Result<(), RustBindingGenerationError> {
    let StructuredInfoTypeShape::Record { fields, .. } = value_type.shape() else {
        return Err(RustBindingGenerationError::InvalidSemanticType);
    };
    writeln!(
        out,
        "#[derive(Debug, Clone, PartialEq, Eq)]\npub struct {name} {{"
    )
    .expect("String writing is infallible");
    for field in fields {
        writeln!(
            out,
            "    {}: {},",
            rust_snake_identifier(field.name())?,
            rust_type(field.value_type(), names)?
        )
        .expect("String writing is infallible");
    }
    writeln!(out, "}}\n").expect("String writing is infallible");
    Ok(())
}

fn emit_semantic_type_impl(out: &mut String, rust_name: &str, constant: &str) {
    writeln!(out, "impl {rust_name} {{").expect("String writing is infallible");
    writeln!(
        out,
        "    pub fn semantic_type() -> Result<StructuredInfoType, NativeBindingRefusal> {{"
    )
    .expect("String writing is infallible");
    writeln!(out, "        StructuredInfoType::from_canonical_bytes({constant}).map_err(NativeBindingRefusal::InvalidSemanticType)")
        .expect("String writing is infallible");
    writeln!(out, "    }}\n}}\n").expect("String writing is infallible");
}

fn rust_type(
    value_type: &StructuredInfoType,
    names: &BTreeMap<String, String>,
) -> Result<String, RustBindingGenerationError> {
    match value_type.shape() {
        StructuredInfoTypeShape::Nominal { schema, .. }
        | StructuredInfoTypeShape::Record { schema, .. }
        | StructuredInfoTypeShape::Variant { schema, .. }
            if names.contains_key(schema.as_str()) =>
        {
            Ok(names[schema.as_str()].clone())
        }
        StructuredInfoTypeShape::Sequence {
            element,
            maximum_items,
            ..
        } => Ok(format!(
            "BoundedSequence<{}, {}>",
            rust_type(element, names)?,
            maximum_items
        )),
        StructuredInfoTypeShape::Variant { schema, cases }
            if schema.as_str() == "conduit.conduitese.optional.v1" =>
        {
            let some = cases
                .iter()
                .find(|case| case.tag() == "some")
                .ok_or(RustBindingGenerationError::InvalidSemanticType)?;
            Ok(format!(
                "Option<{}>",
                rust_type(some.payload_type(), names)?
            ))
        }
        StructuredInfoTypeShape::Leaf(kind) => primitive_rust_type(kind.as_str()),
        _ => Err(RustBindingGenerationError::InvalidSemanticType),
    }
}

fn primitive_rust_type(identity: &str) -> Result<String, RustBindingGenerationError> {
    let value = match conduit_core::primitive_info_kind(identity) {
        Some(PrimitiveInfoKind::Unit | PrimitiveInfoKind::CancellationRequest) => "()",
        Some(PrimitiveInfoKind::Bool) => "conduit_core::InfoBool",
        Some(PrimitiveInfoKind::Count) => "u64",
        Some(PrimitiveInfoKind::Scalar) => "conduit_core::Scalar",
        Some(PrimitiveInfoKind::Text) => "String",
        Some(PrimitiveInfoKind::Bytes) | None
            if identity.starts_with("data/generation-reference<") =>
        {
            "BoundedBytes<4096>"
        }
        Some(PrimitiveInfoKind::Bytes) => "BoundedBytes<4096>",
        Some(
            PrimitiveInfoKind::Quantity
            | PrimitiveInfoKind::Distance
            | PrimitiveInfoKind::Frequency
            | PrimitiveInfoKind::Duration
            | PrimitiveInfoKind::Voltage
            | PrimitiveInfoKind::Temperature
            | PrimitiveInfoKind::Angle
            | PrimitiveInfoKind::Ratio
            | PrimitiveInfoKind::PixelCount,
        ) => "conduit_core::Quantity",
        Some(PrimitiveInfoKind::U8) => "u8",
        Some(PrimitiveInfoKind::U16) => "u16",
        Some(PrimitiveInfoKind::U32) => "u32",
        Some(PrimitiveInfoKind::U64) => "u64",
        Some(PrimitiveInfoKind::U128) => "u128",
        Some(PrimitiveInfoKind::I8) => "i8",
        Some(PrimitiveInfoKind::I16) => "i16",
        Some(PrimitiveInfoKind::I32) => "i32",
        Some(PrimitiveInfoKind::I64) => "i64",
        Some(PrimitiveInfoKind::I128) => "i128",
        Some(PrimitiveInfoKind::Terminal) | None => {
            return Err(RustBindingGenerationError::UnsupportedLeaf(identity.into()))
        }
    };
    Ok(value.into())
}

fn unit_type(value_type: &StructuredInfoType) -> bool {
    matches!(value_type.shape(), StructuredInfoTypeShape::Leaf(kind) if kind.as_str() == conduit_core::UNIT_INFO_ID)
}

fn rust_pascal_identifier(value: &str) -> Result<String, RustBindingGenerationError> {
    rust_identifier(value, true)
}

fn rust_snake_identifier(value: &str) -> Result<String, RustBindingGenerationError> {
    rust_identifier(value, false)
}

fn rust_screaming_identifier(value: &str) -> Result<String, RustBindingGenerationError> {
    rust_identifier(value, false).map(|value| value.to_ascii_uppercase())
}

fn rust_identifier(value: &str, pascal: bool) -> Result<String, RustBindingGenerationError> {
    let mut output = String::new();
    for part in value.split(|character: char| !character.is_ascii_alphanumeric()) {
        if part.is_empty() {
            continue;
        }
        if pascal {
            let mut characters = part.chars();
            if let Some(first) = characters.next() {
                output.push(first.to_ascii_uppercase());
                output.extend(characters);
            }
        } else {
            if !output.is_empty() {
                output.push('_');
            }
            output.push_str(&part.to_ascii_lowercase());
        }
    }
    if output.is_empty()
        || output.as_bytes()[0].is_ascii_digit()
        || (!pascal && RUST_KEYWORDS.contains(&output.as_str()))
    {
        return Err(RustBindingGenerationError::InvalidRustIdentifier(
            value.into(),
        ));
    }
    Ok(output)
}

fn byte_literals(bytes: &[u8]) -> String {
    bytes
        .iter()
        .map(|byte| format!("0x{byte:02x}"))
        .collect::<Vec<_>>()
        .join(", ")
}

const RUST_KEYWORDS: &[&str] = &[
    "as", "break", "const", "continue", "crate", "else", "enum", "extern", "false", "fn", "for",
    "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref", "return",
    "self", "Self", "static", "struct", "super", "trait", "true", "type", "unsafe", "use", "where",
    "while", "async", "await", "dyn",
];

#[cfg(test)]
mod tests {
    use super::*;

    fn checked_types() -> Vec<CheckedNativeType> {
        let source = r#"type Note = U8 in 0..=127

type Position = {
    x: Distance
    y: Distance
}

type MusicEvent =
    note {
        velocity: U8 in 0..=127
        pitches: sequence Note <= 16
    }
    | rest
"#;
        crate::check_syntax_document(
            &crate::parse_syntax_document(source),
            &crate::StartupCatalog::new(),
        )
        .unwrap()
        .native_types
    }

    #[test]
    fn generation_is_deterministic_and_keeps_rust_spelling_out_of_identity() {
        let types = checked_types();
        let plain = generate_rust_bindings(&types, &RustBindingOptions::default()).unwrap();
        assert_eq!(
            plain,
            generate_rust_bindings(&types, &RustBindingOptions::default()).unwrap()
        );
        let prefixed = generate_rust_bindings(
            &types,
            &RustBindingOptions {
                type_prefix: "Fixture".into(),
            },
        )
        .unwrap();
        assert_eq!(plain.semantic_type_bytes, prefixed.semantic_type_bytes);
        assert!(plain.source.contains("pub struct Note(u8);"));
        assert!(plain.source.contains("pub struct Position {"));
        assert!(plain.source.contains("pub enum MusicEvent {"));
        assert!(plain.source.contains("pitches: BoundedSequence<Note, 16>"));
        assert!(plain.source.contains("Note(MusicEventNote)"));
        assert!(plain.source.contains("Rest,"));
        assert!(prefixed.source.contains("pub struct FixtureNote(u8);"));
    }

    #[test]
    fn colliding_or_invalid_rust_spellings_refuse_instead_of_rebinding() {
        let mut types = checked_types();
        types[1].name = "note".into();
        assert!(matches!(
            generate_rust_bindings(&types, &RustBindingOptions::default()),
            Err(RustBindingGenerationError::DuplicateRustIdentifier(name)) if name == "Note"
        ));
        assert_eq!(
            generate_rust_bindings(
                &checked_types(),
                &RustBindingOptions {
                    type_prefix: "9".into(),
                },
            ),
            Err(RustBindingGenerationError::InvalidRustIdentifier(
                "9".into()
            ))
        );
    }
}
