use crate::prelude::*;
use crate::{CheckedCode, CheckedNativeType};
use alloc::collections::{BTreeMap, BTreeSet};
use conduit_core::{PrimitiveInfoKind, StructuredInfoType, StructuredInfoTypeShape};
use core::fmt::Write;

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct RustBindingOptions {
    /// A Rust-only spelling prefix. It never participates in semantic identity.
    pub type_prefix: String,
    /// Adds code-only Serde derives to variants whose generated Rust payloads
    /// also support Serde.
    /// This never participates in semantic identity and requires the consuming
    /// crate to provide `serde` with derive support.
    pub derive_serde_for_variants: bool,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RustBindingModule {
    pub source: String,
    pub semantic_type_bytes: BTreeMap<String, Vec<u8>>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RustBindingGenerationError {
    EmptyTypeSet,
    InvalidRustIdentifier(String),
    DuplicateRustIdentifier(String),
    InvalidSemanticType,
    UnsupportedLeaf(String),
}

pub fn generate_rust_bindings(
    types: &[CheckedNativeType],
    options: &RustBindingOptions,
) -> Result<RustBindingModule, RustBindingGenerationError> {
    generate_rust_bindings_with_codes(types, &[], options)
}

pub fn generate_rust_bindings_with_codes(
    types: &[CheckedNativeType],
    codes: &[CheckedCode],
    options: &RustBindingOptions,
) -> Result<RustBindingModule, RustBindingGenerationError> {
    if types.is_empty() {
        return Err(RustBindingGenerationError::EmptyTypeSet);
    }
    let mut names = BTreeMap::new();
    let mut seen = BTreeSet::new();
    let mut semantic_type_bytes = BTreeMap::new();
    for value_type in types {
        let prefix = if options.type_prefix.is_empty() {
            String::new()
        } else {
            rust_pascal_identifier(&options.type_prefix)?
        };
        let rust_name = format!("{}{}", prefix, rust_pascal_identifier(&value_type.name)?);
        if !seen.insert(rust_name.clone()) {
            return Err(RustBindingGenerationError::DuplicateRustIdentifier(
                rust_name,
            ));
        }
        names.insert(value_type.identity.as_str().to_string(), rust_name);
        semantic_type_bytes.insert(
            value_type.identity.as_str().to_string(),
            value_type
                .value_type
                .canonical_bytes()
                .map_err(|_| RustBindingGenerationError::InvalidSemanticType)?,
        );
    }

    let mut source = String::from(
        "// @generated by Conduit from checked semantic Types.\n\
         // Rust names and layout are bindings, never semantic identity.\n\
         extern crate alloc;\n\
         #[allow(unused_imports)]\n\
         use conduit_form::rust_binding::{BoundedBytes, BoundedSequence, NativeBindingRefusal, NativeCodeRefusal, NativeRustBinding};\n\
         use conduit_form::rust_binding::semantic_core as conduit_core;\n\
         #[allow(unused_imports)]\n\
         use conduit_core::{StructuredFieldValue, StructuredInfoType, StructuredInfoValue, StructuredInfoValueShape};\n\
         #[allow(unused_imports)]\n\
         use alloc::{string::String, vec, vec::Vec};\n\n",
    );
    for value_type in types {
        emit_type(
            &mut source,
            value_type,
            &names,
            &semantic_type_bytes,
            options,
        )?;
    }
    emit_codes(&mut source, codes, &names)?;
    Ok(RustBindingModule {
        source,
        semantic_type_bytes,
    })
}

fn emit_codes(
    out: &mut String,
    codes: &[CheckedCode],
    names: &BTreeMap<String, String>,
) -> Result<(), RustBindingGenerationError> {
    let mut codec_names = BTreeSet::new();
    for code in codes {
        let rust_type = names
            .get(code.value_type.as_str())
            .ok_or(RustBindingGenerationError::InvalidSemanticType)?;
        let codec = format!("{rust_type}Code");
        if !codec_names.insert(codec.clone()) {
            return Err(RustBindingGenerationError::DuplicateRustIdentifier(codec));
        }
        writeln!(out, "pub struct {codec};").expect("String writing is infallible");
        writeln!(out, "impl {codec} {{").expect("String writing is infallible");
        writeln!(out, "    pub const NAME: &str = {:?};", code.name)
            .expect("String writing is infallible");
        writeln!(
            out,
            "    pub const IDENTITY: &str = {:?};",
            code.compatibility_id
        )
        .expect("String writing is infallible");
        writeln!(
            out,
            "    pub const EXACT_BYTES: usize = {};",
            code.exact_bytes
        )
        .expect("String writing is infallible");
        writeln!(
            out,
            "    pub const MAXIMUM_BYTES: usize = {};",
            code.maximum_bytes
        )
        .expect("String writing is infallible");
        writeln!(
            out,
            "    pub const MAXIMUM_DECODE_STEPS: usize = {};",
            code.maximum_decode_steps
        )
        .expect("String writing is infallible");
        writeln!(
            out,
            "    pub const fn encode(value: {rust_type}) -> [u8; 1] {{"
        )
        .expect("String writing is infallible");
        writeln!(out, "        [match value {{").expect("String writing is infallible");
        for mapping in &code.mappings {
            writeln!(
                out,
                "            {rust_type}::{} => {},",
                rust_pascal_identifier(&mapping.variant)?,
                mapping.discriminant
            )
            .expect("String writing is infallible");
        }
        writeln!(out, "        }}]").expect("String writing is infallible");
        writeln!(out, "    }}").expect("String writing is infallible");
        writeln!(
            out,
            "    pub fn decode(encoded: &[u8]) -> Result<{rust_type}, NativeCodeRefusal> {{"
        )
        .expect("String writing is infallible");
        writeln!(out, "        let [tag] = encoded else {{ return Err(NativeCodeRefusal::WrongLength {{ actual: encoded.len() }}); }};")
            .expect("String writing is infallible");
        writeln!(out, "        match *tag {{").expect("String writing is infallible");
        for mapping in &code.mappings {
            writeln!(
                out,
                "            {} => Ok({rust_type}::{}),",
                mapping.discriminant,
                rust_pascal_identifier(&mapping.variant)?
            )
            .expect("String writing is infallible");
        }
        writeln!(
            out,
            "            actual => Err(NativeCodeRefusal::InvalidTag {{ actual }}),"
        )
        .expect("String writing is infallible");
        writeln!(out, "        }}").expect("String writing is infallible");
        writeln!(out, "    }}\n}}\n").expect("String writing is infallible");
    }
    Ok(())
}

fn emit_type(
    out: &mut String,
    value_type: &CheckedNativeType,
    names: &BTreeMap<String, String>,
    bytes_by_identity: &BTreeMap<String, Vec<u8>>,
    options: &RustBindingOptions,
) -> Result<(), RustBindingGenerationError> {
    let rust_name = &names[value_type.identity.as_str()];
    let constant = format!("{}_SEMANTIC_TYPE", rust_screaming_identifier(rust_name)?);
    let bytes = &bytes_by_identity[value_type.identity.as_str()];
    writeln!(
        out,
        "pub const {constant}: &[u8] = &[{}];",
        byte_literals(bytes)
    )
    .expect("String writing is infallible");
    writeln!(
        out,
        "pub const {constant}_IDENTITY: &str = {:?};",
        value_type.identity.as_str()
    )
    .expect("String writing is infallible");

    match value_type.value_type.shape() {
        StructuredInfoTypeShape::Nominal { representation, .. } => {
            let inner = rust_type(representation, names)?;
            writeln!(
                out,
                "#[derive(Debug, Clone, PartialEq, Eq)]\npub struct {rust_name}({inner});"
            )
            .expect("String writing is infallible");
            writeln!(out, "impl {rust_name} {{").expect("String writing is infallible");
            writeln!(out, "    pub fn get(&self) -> &{inner} {{ &self.0 }}")
                .expect("String writing is infallible");
            writeln!(out, "}}\n").expect("String writing is infallible");
        }
        StructuredInfoTypeShape::Record { fields, .. } => {
            writeln!(
                out,
                "#[derive(Debug, Clone, PartialEq, Eq)]\npub struct {rust_name} {{"
            )
            .expect("String writing is infallible");
            for field in fields {
                writeln!(
                    out,
                    "    {}: {},",
                    rust_snake_identifier(field.name())?,
                    rust_type(field.value_type(), names)?
                )
                .expect("String writing is infallible");
            }
            writeln!(out, "}}\n").expect("String writing is infallible");
        }
        StructuredInfoTypeShape::Variant { cases, .. } => {
            let unit_only = cases.iter().all(|case| unit_type(case.payload_type()));
            for case in cases {
                if matches!(
                    case.payload_type().shape(),
                    StructuredInfoTypeShape::Record { .. }
                ) {
                    let payload = format!("{rust_name}{}", rust_pascal_identifier(case.tag())?);
                    emit_payload_struct(
                        out,
                        &payload,
                        case.payload_type(),
                        names,
                        options.derive_serde_for_variants,
                    )?;
                }
            }
            let copy_payloads = cases.iter().all(|case| {
                !matches!(
                    case.payload_type().shape(),
                    StructuredInfoTypeShape::Record { .. }
                ) && copy_type(case.payload_type())
            });
            let derives = if unit_only && options.derive_serde_for_variants {
                "Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, serde::Serialize, serde::Deserialize"
            } else if unit_only {
                "Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash"
            } else if copy_payloads && options.derive_serde_for_variants {
                "Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize"
            } else if copy_payloads {
                "Debug, Clone, Copy, PartialEq, Eq"
            } else if options.derive_serde_for_variants {
                "Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize"
            } else {
                "Debug, Clone, PartialEq, Eq"
            };
            writeln!(out, "#[derive({derives})]\npub enum {rust_name} {{")
                .expect("String writing is infallible");
            for case in cases {
                let variant = rust_pascal_identifier(case.tag())?;
                if unit_type(case.payload_type()) {
                    writeln!(out, "    {variant},").expect("String writing is infallible");
                } else if matches!(
                    case.payload_type().shape(),
                    StructuredInfoTypeShape::Record { .. }
                ) {
                    writeln!(out, "    {variant}({rust_name}{variant}),")
                        .expect("String writing is infallible");
                } else {
                    writeln!(
                        out,
                        "    {variant}({}),",
                        rust_type(case.payload_type(), names)?
                    )
                    .expect("String writing is infallible");
                }
            }
            writeln!(out, "}}\n").expect("String writing is infallible");
        }
        _ => return Err(RustBindingGenerationError::InvalidSemanticType),
    }
    emit_semantic_type_impl(out, rust_name, &constant);
    super::generate_value::emit_value_impl(out, value_type, rust_name, &constant, names)?;
    Ok(())
}

fn emit_payload_struct(
    out: &mut String,
    name: &str,
    value_type: &StructuredInfoType,
    names: &BTreeMap<String, String>,
    derive_serde: bool,
) -> Result<(), RustBindingGenerationError> {
    let StructuredInfoTypeShape::Record { fields, .. } = value_type.shape() else {
        return Err(RustBindingGenerationError::InvalidSemanticType);
    };
    let derives = if derive_serde {
        "Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize"
    } else {
        "Debug, Clone, PartialEq, Eq"
    };
    writeln!(out, "#[derive({derives})]\npub struct {name} {{")
        .expect("String writing is infallible");
    for field in fields {
        writeln!(
            out,
            "    {}: {},",
            rust_snake_identifier(field.name())?,
            rust_type(field.value_type(), names)?
        )
        .expect("String writing is infallible");
    }
    writeln!(out, "}}\n\nimpl {name} {{").expect("String writing is infallible");
    for field in fields {
        let field_name = rust_snake_identifier(field.name())?;
        let field_type = rust_type(field.value_type(), names)?;
        writeln!(
            out,
            "    pub fn {field_name}(&self) -> &{field_type} {{ &self.{field_name} }}"
        )
        .expect("String writing is infallible");
    }
    writeln!(out, "}}\n").expect("String writing is infallible");
    Ok(())
}

pub(super) fn copy_type(value_type: &StructuredInfoType) -> bool {
    match value_type.shape() {
        StructuredInfoTypeShape::Leaf(kind) => !matches!(
            conduit_core::primitive_info_kind(kind.as_str()),
            Some(PrimitiveInfoKind::Text | PrimitiveInfoKind::Bytes) | None
        ),
        StructuredInfoTypeShape::Nominal { representation, .. } => copy_type(representation),
        StructuredInfoTypeShape::Record { fields, .. } => {
            fields.iter().all(|field| copy_type(field.value_type()))
        }
        StructuredInfoTypeShape::Variant { cases, .. } => {
            cases.iter().all(|case| copy_type(case.payload_type()))
        }
        StructuredInfoTypeShape::Sequence { .. } | StructuredInfoTypeShape::Collection { .. } => {
            false
        }
    }
}

fn emit_semantic_type_impl(out: &mut String, rust_name: &str, constant: &str) {
    writeln!(out, "impl {rust_name} {{").expect("String writing is infallible");
    writeln!(
        out,
        "    pub fn semantic_type() -> Result<StructuredInfoType, NativeBindingRefusal> {{"
    )
    .expect("String writing is infallible");
    writeln!(out, "        StructuredInfoType::from_canonical_bytes({constant}).map_err(NativeBindingRefusal::InvalidSemanticType)")
        .expect("String writing is infallible");
    writeln!(out, "    }}\n}}\n").expect("String writing is infallible");
}

pub(super) fn rust_type(
    value_type: &StructuredInfoType,
    names: &BTreeMap<String, String>,
) -> Result<String, RustBindingGenerationError> {
    match value_type.shape() {
        StructuredInfoTypeShape::Nominal { schema, .. }
        | StructuredInfoTypeShape::Record { schema, .. }
        | StructuredInfoTypeShape::Variant { schema, .. }
            if names.contains_key(schema.as_str()) =>
        {
            Ok(names[schema.as_str()].clone())
        }
        StructuredInfoTypeShape::Sequence {
            element,
            maximum_items,
            ..
        } => Ok(format!(
            "BoundedSequence<{}, {}>",
            rust_type(element, names)?,
            maximum_items
        )),
        StructuredInfoTypeShape::Variant { schema, cases }
            if schema.as_str() == "conduit.conduitese.optional.v1" =>
        {
            let some = cases
                .iter()
                .find(|case| case.tag() == "some")
                .ok_or(RustBindingGenerationError::InvalidSemanticType)?;
            Ok(format!(
                "Option<{}>",
                rust_type(some.payload_type(), names)?
            ))
        }
        StructuredInfoTypeShape::Leaf(kind) => primitive_rust_type(kind.as_str()),
        _ => Err(RustBindingGenerationError::InvalidSemanticType),
    }
}

pub(super) fn primitive_rust_type(identity: &str) -> Result<String, RustBindingGenerationError> {
    let value = match conduit_core::primitive_info_kind(identity) {
        Some(PrimitiveInfoKind::Unit | PrimitiveInfoKind::CancellationRequest) => "()",
        Some(PrimitiveInfoKind::Bool) => "bool",
        Some(PrimitiveInfoKind::Count) => "u64",
        Some(PrimitiveInfoKind::Scalar) => "conduit_core::Scalar",
        Some(PrimitiveInfoKind::Text) => "String",
        Some(PrimitiveInfoKind::Bytes) | None
            if identity.starts_with("data/generation-reference<") =>
        {
            "BoundedBytes<4096>"
        }
        Some(PrimitiveInfoKind::Bytes) => "BoundedBytes<4096>",
        Some(
            PrimitiveInfoKind::Quantity
            | PrimitiveInfoKind::Distance
            | PrimitiveInfoKind::Frequency
            | PrimitiveInfoKind::Duration
            | PrimitiveInfoKind::Voltage
            | PrimitiveInfoKind::Temperature
            | PrimitiveInfoKind::Angle
            | PrimitiveInfoKind::Ratio
            | PrimitiveInfoKind::PixelCount,
        ) => "conduit_core::Quantity",
        Some(PrimitiveInfoKind::U8) => "u8",
        Some(PrimitiveInfoKind::U16) => "u16",
        Some(PrimitiveInfoKind::U32) => "u32",
        Some(PrimitiveInfoKind::U64) => "u64",
        Some(PrimitiveInfoKind::U128) => "u128",
        Some(PrimitiveInfoKind::I8) => "i8",
        Some(PrimitiveInfoKind::I16) => "i16",
        Some(PrimitiveInfoKind::I32) => "i32",
        Some(PrimitiveInfoKind::I64) => "i64",
        Some(PrimitiveInfoKind::I128) => "i128",
        Some(PrimitiveInfoKind::Terminal) | None => {
            return Err(RustBindingGenerationError::UnsupportedLeaf(identity.into()));
        }
    };
    Ok(value.into())
}

pub(super) fn unit_type(value_type: &StructuredInfoType) -> bool {
    matches!(value_type.shape(), StructuredInfoTypeShape::Leaf(kind) if kind.as_str() == conduit_core::UNIT_INFO_ID)
}

pub(super) fn rust_pascal_identifier(value: &str) -> Result<String, RustBindingGenerationError> {
    rust_identifier(value, true)
}

pub(super) fn rust_snake_identifier(value: &str) -> Result<String, RustBindingGenerationError> {
    rust_identifier(value, false)
}

fn rust_screaming_identifier(value: &str) -> Result<String, RustBindingGenerationError> {
    rust_identifier(value, false).map(|value| value.to_ascii_uppercase())
}

fn rust_identifier(value: &str, pascal: bool) -> Result<String, RustBindingGenerationError> {
    let mut output = String::new();
    for part in value.split(|character: char| !character.is_ascii_alphanumeric()) {
        if part.is_empty() {
            continue;
        }
        if pascal {
            let mut characters = part.chars();
            if let Some(first) = characters.next() {
                output.push(first.to_ascii_uppercase());
                output.extend(characters);
            }
        } else {
            if !output.is_empty() {
                output.push('_');
            }
            output.push_str(&part.to_ascii_lowercase());
        }
    }
    if output.is_empty()
        || output.as_bytes()[0].is_ascii_digit()
        || (!pascal && RUST_KEYWORDS.contains(&output.as_str()))
    {
        return Err(RustBindingGenerationError::InvalidRustIdentifier(
            value.into(),
        ));
    }
    Ok(output)
}

fn byte_literals(bytes: &[u8]) -> String {
    bytes
        .iter()
        .map(|byte| format!("0x{byte:02x}"))
        .collect::<Vec<_>>()
        .join(", ")
}

const RUST_KEYWORDS: &[&str] = &[
    "as", "break", "const", "continue", "crate", "else", "enum", "extern", "false", "fn", "for",
    "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref", "return",
    "self", "Self", "static", "struct", "super", "trait", "true", "type", "unsafe", "use", "where",
    "while", "async", "await", "dyn",
];
