//! Finite admission bounds for the first region realization profile.

use crate::REACTION_DIFFUSION_MAXIMUM_CELLS;

pub const REACTION_DIFFUSION_MAXIMUM_REGIONS: u16 = 16;
pub const REACTION_DIFFUSION_MAXIMUM_BOUNDARIES: u32 = 4_096;
pub const REACTION_DIFFUSION_MAXIMUM_BOUNDARY_VALUES: u32 = 4_096;
pub const REACTION_DIFFUSION_MAXIMUM_GENERATIONS_IN_FLIGHT: u16 = 1;
pub const REACTION_DIFFUSION_MAXIMUM_PARTITION_WORK: u32 = REACTION_DIFFUSION_MAXIMUM_CELLS;
pub const REACTION_DIFFUSION_MAXIMUM_RETAINED_REGION_CELLS: u32 = REACTION_DIFFUSION_MAXIMUM_CELLS;
pub const REACTION_DIFFUSION_MAXIMUM_OPERATION_CELLS: u32 =
    REACTION_DIFFUSION_MAXIMUM_RETAINED_REGION_CELLS
        + REACTION_DIFFUSION_MAXIMUM_BOUNDARY_VALUES
        + REACTION_DIFFUSION_MAXIMUM_CELLS;
pub const REACTION_DIFFUSION_BOUNDARY_HEADER_BYTES: usize = 50;
pub const REACTION_DIFFUSION_MAXIMUM_BOUNDARY_BYTES: u32 =
    REACTION_DIFFUSION_MAXIMUM_BOUNDARY_VALUES * 8
        + REACTION_DIFFUSION_MAXIMUM_BOUNDARIES * REACTION_DIFFUSION_BOUNDARY_HEADER_BYTES as u32;
