use crate::prelude::*;
use crate::CheckedRepresentation;
use core::fmt::Write;

/// Emits an ECMAScript consumer from checked representation facts.
pub fn generate_ecmascript_representations(representations: &[CheckedRepresentation]) -> String {
    let mut out = String::from(
        "// @generated by Conduit from checked representations.\n\
         export class RepresentationRefusal extends Error {\n\
           constructor(identity, kind, actual) {\n\
             super(`${identity}: ${kind} (${actual})`);\n\
             this.identity = identity; this.kind = kind; this.actual = actual;\n\
           }\n\
         }\n\
         export const representations = Object.freeze({\n",
    );
    for representation in representations {
        writeln!(
            out,
            "  {:?}: Object.freeze({{ compatibility: {:?}, exactBytes: {}, maximumBytes: {}, maximumDecodeSteps: {}, invalid: {:?}, mappings: Object.freeze({{",
            representation.name,
            representation.compatibility_id,
            representation.exact_bytes,
            representation.maximum_bytes,
            representation.maximum_decode_steps,
            representation.invalid_refusal.as_str(),
        )
        .expect("String writing is infallible");
        for mapping in &representation.mappings {
            writeln!(out, "    {:?}: {},", mapping.variant, mapping.discriminant)
                .expect("String writing is infallible");
        }
        writeln!(out, "  }}) }}),").expect("String writing is infallible");
    }
    out.push_str(
        "});\n\
         function declared(identity) {\n\
           const value = representations[identity];\n\
           if (!value) throw new RepresentationRefusal(identity, 'unknown_representation', identity);\n\
           return value;\n\
         }\n\
         export function encode(identity, variant) {\n\
           const representation = declared(identity);\n\
           const tag = representation.mappings[variant];\n\
           if (tag === undefined) throw new RepresentationRefusal(identity, 'unknown_variant', variant);\n\
           return Uint8Array.of(tag);\n\
         }\n\
         export function decode(identity, encoded) {\n\
           const representation = declared(identity);\n\
           if (encoded.length !== representation.exactBytes)\n\
             throw new RepresentationRefusal(identity, 'wrong_length', encoded.length);\n\
           for (const [variant, tag] of Object.entries(representation.mappings))\n\
             if (tag === encoded[0]) return variant;\n\
           throw new RepresentationRefusal(identity, representation.invalid, encoded[0]);\n\
         }\n",
    );
    out
}
