use crate::prelude::*;
use crate::{CheckedNativeType, CheckedTypeForm};
use alloc::collections::BTreeMap;
use conduit_core::{StructuredInfoType, StructuredInfoTypeShape};
use core::fmt::Write;

const OPTIONAL_SCHEMA: &str = "conduit.conduitese.optional.v1";

/// Emits exact, immutable ECMAScript descriptors for checked semantic Types.
///
/// This is an inspection binding: the checked canonical schema and primitive
/// bounds remain the source of truth. It does not create a second validator.
pub fn generate_ecmascript_types(types: &[CheckedNativeType]) -> String {
    let names = types
        .iter()
        .map(|native| (native.identity.as_str().to_string(), native.name.clone()))
        .collect::<BTreeMap<_, _>>();
    let mut out = String::from(
        "// @generated by Conduit from checked semantic Types.\n\
         export class TypeRefusal extends Error {\n\
           constructor(name) { super(`unknown semantic Type: ${name}`); this.typeName = name; }\n\
         }\n\
         export const semanticTypes = Object.freeze({\n",
    );
    for native in types {
        let shape = emit_type_shape(&native.value_type, native.identity.as_str(), &names);
        let canonical = emit_bytes(
            &native
                .value_type
                .canonical_bytes()
                .expect("checked semantic Type has canonical bytes"),
        );
        writeln!(
            out,
            "  {:?}: Object.freeze({{ identity: {:?}, canonicalType: Object.freeze({canonical}), contracts: Object.freeze([",
            native.name,
            native.identity.as_str(),
        )
        .expect("String writing is infallible");
        for retained in &native.value_contracts {
            let contract_identity = emit_bytes(&retained.contract.identity_bytes());
            writeln!(
                out,
                "    Object.freeze({{ path: {:?}, valueKind: {:?}, maximumBytes: {}, identity: Object.freeze({contract_identity}) }}),",
                retained.representation_path,
                retained.contract.value_kind.as_str(),
                retained.contract.maximum_bytes,
            )
            .expect("String writing is infallible");
        }
        writeln!(out, "  ]), shape: {shape} }}),").expect("String writing is infallible");
    }
    out.push_str(
        "});\n\
         export function inspectIeee(identity, encoded) {\n\
           const width = identity === 'value/ieee754-binary32' ? 4 : identity === 'value/ieee754-binary64' ? 8 : 0;\n\
           if (!width || encoded.length !== width) throw new TypeRefusal(identity);\n\
           let bits = 0n;\n\
           for (let index = width - 1; index >= 0; index--) bits = (bits << 8n) | BigInt(encoded[index]);\n\
           const fractionBits = width === 4 ? 23n : 52n;\n\
           const exponentBits = width === 4 ? 8n : 11n;\n\
           const fractionMask = (1n << fractionBits) - 1n;\n\
           const exponentMask = (1n << exponentBits) - 1n;\n\
           const fraction = bits & fractionMask;\n\
           const exponent = (bits >> fractionBits) & exponentMask;\n\
           const sign = Number(bits >> (fractionBits + exponentBits));\n\
           return Object.freeze({ bits, sign, exponent, fraction, finite: exponent !== exponentMask, nan: exponent === exponentMask && fraction !== 0n, infinity: exponent === exponentMask && fraction === 0n, signedZero: exponent === 0n && fraction === 0n });\n\
         }\n\
         export function lookupType(name) {\n\
           const value = Object.hasOwn(semanticTypes, name) ? semanticTypes[name] : undefined;\n\
           if (!value) throw new TypeRefusal(name);\n\
           return value;\n\
         }\n",
    );
    out
}

fn emit_type_shape(
    value_type: &StructuredInfoType,
    root_identity: &str,
    names: &BTreeMap<String, String>,
) -> String {
    if let Some(identity) = schema_identity(value_type) {
        if identity != root_identity {
            if let Some(name) = names.get(identity) {
                return format!(
                    "Object.freeze({{ kind: 'reference', name: {name:?}, identity: {identity:?} }})"
                );
            }
        }
    }
    match value_type.shape() {
        StructuredInfoTypeShape::Leaf(kind) => format!(
            "Object.freeze({{ kind: 'leaf', identity: {:?} }})",
            kind.as_str()
        ),
        StructuredInfoTypeShape::Nominal {
            schema,
            representation,
        } => format!(
            "Object.freeze({{ kind: 'nominal', identity: {:?}, representation: {} }})",
            schema.as_str(),
            emit_type_shape(representation, root_identity, names)
        ),
        StructuredInfoTypeShape::Collection { element, length } => format!(
            "Object.freeze({{ kind: 'collection', length: {length}, element: {} }})",
            emit_type_shape(element, root_identity, names)
        ),
        StructuredInfoTypeShape::Sequence {
            element,
            minimum_items,
            maximum_items,
        } => format!(
            "Object.freeze({{ kind: 'sequence', minimumItems: {minimum_items}, maximumItems: {maximum_items}, element: {} }})",
            emit_type_shape(element, root_identity, names)
        ),
        StructuredInfoTypeShape::Record { schema, fields } => {
            let fields = fields
                .iter()
                .map(|field| {
                    format!(
                        "Object.freeze({{ name: {:?}, value: {} }})",
                        field.name(),
                        emit_type_shape(field.value_type(), root_identity, names)
                    )
                })
                .collect::<Vec<_>>()
                .join(", ");
            format!(
                "Object.freeze({{ kind: 'record', identity: {:?}, fields: Object.freeze([{fields}]) }})",
                schema.as_str()
            )
        }
        StructuredInfoTypeShape::Variant { schema, cases }
            if schema.as_str() == OPTIONAL_SCHEMA =>
        {
            let some = cases
                .iter()
                .find(|case| case.tag() == "some")
                .expect("checked optional carries some");
            format!(
                "Object.freeze({{ kind: 'optional', value: {} }})",
                emit_type_shape(some.payload_type(), root_identity, names)
            )
        }
        StructuredInfoTypeShape::Variant { schema, cases } => {
            let cases = cases
                .iter()
                .map(|case| {
                    format!(
                        "Object.freeze({{ tag: {:?}, value: {} }})",
                        case.tag(),
                        emit_type_shape(case.payload_type(), root_identity, names)
                    )
                })
                .collect::<Vec<_>>()
                .join(", ");
            format!(
                "Object.freeze({{ kind: 'variant', identity: {:?}, cases: Object.freeze([{cases}]) }})",
                schema.as_str()
            )
        }
    }
}

fn schema_identity(value_type: &StructuredInfoType) -> Option<&str> {
    match value_type.shape() {
        StructuredInfoTypeShape::Nominal { schema, .. }
        | StructuredInfoTypeShape::Record { schema, .. }
        | StructuredInfoTypeShape::Variant { schema, .. } => Some(schema.as_str()),
        _ => None,
    }
}

fn emit_bytes(bytes: &[u8]) -> String {
    format!(
        "[{}]",
        bytes
            .iter()
            .map(u8::to_string)
            .collect::<Vec<_>>()
            .join(", ")
    )
}

/// Emits an ECMAScript consumer from checked Form facts.
pub fn generate_ecmascript_forms(type_forms: &[CheckedTypeForm]) -> String {
    let mut out = String::from(
        "// @generated by Conduit from checked Forms.\n\
         export class FormRefusal extends Error {\n\
           constructor(identity, kind, actual) {\n\
             super(`${identity}: ${kind} (${actual})`);\n\
             this.identity = identity; this.kind = kind; this.actual = actual;\n\
           }\n\
         }\n\
         export const forms = Object.freeze({\n",
    );
    for form in type_forms {
        writeln!(
            out,
            "  {:?}: Object.freeze({{ compatibility: {:?}, exactBytes: {}, maximumBytes: {}, maximumDecodeSteps: {}, invalid: {:?}, mappings: Object.freeze({{",
            form.name,
            form.compatibility_id,
            form.exact_bytes,
            form.maximum_bytes,
            form.maximum_decode_steps,
            form.invalid_refusal.as_str(),
        )
        .expect("String writing is infallible");
        for mapping in &form.mappings {
            writeln!(out, "    {:?}: {},", mapping.variant, mapping.discriminant)
                .expect("String writing is infallible");
        }
        writeln!(out, "  }}) }}),").expect("String writing is infallible");
    }
    out.push_str(
        "});\n\
         function declared(identity) {\n\
           const value = forms[identity];\n\
           if (!value) throw new FormRefusal(identity, 'unknown_form', identity);\n\
           return value;\n\
         }\n\
         export function encode(identity, variant) {\n\
           const form = declared(identity);\n\
           const tag = form.mappings[variant];\n\
           if (tag === undefined) throw new FormRefusal(identity, 'unknown_variant', variant);\n\
           return Uint8Array.of(tag);\n\
         }\n\
         export function decode(identity, encoded) {\n\
           const form = declared(identity);\n\
           if (encoded.length !== form.exactBytes)\n\
             throw new FormRefusal(identity, 'wrong_length', encoded.length);\n\
           for (const [variant, tag] of Object.entries(form.mappings))\n\
             if (tag === encoded[0]) return variant;\n\
           throw new FormRefusal(identity, form.invalid, encoded[0]);\n\
         }\n",
    );
    out
}
