timeout: 0
serial: yes

/ConduitOS AArch64 A1
    protocol: limine
    path: boot():/boot/conduitos
    cmdline: profile=conduitos/aarch64-entry-only@1
    module_path: boot():/boot/conduit-spore.bin
    module_string: conduit.spore/native-media-provision@1
