timeout: 0
serial: yes

/ConduitOS
    protocol: limine
    path: boot():/boot/conduitos
    cmdline: profile=conduitos/x86_64-single-lane@1
    module_path: boot():/boot/conduit-spore.bin
    module_string: conduit.spore/native-media-provision@1
